---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
helmCharts:
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts
    version: 0.32.1
    releaseName: intel-device-plugins-operator
    valuesFile: values.yaml
