---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-server
  namespace: flux-system
spec:
  path: ./kubernetes/pitower/apps/tools/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
