---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.io/charts/
    version: 0.24.0
    releaseName: cloudnative-pg
    includeCRDs: true
    valuesFile: values.yaml
    namespace: database