# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: firefly-secret
    labels:
        app.kubernetes.io/name: firefly
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:stmny5FsplUdTH80n1OVHHLyy7hIR4+RWg3d+jcwdUw=,iv:fi1X8WX6NVXIaJ9N6kV+o7Gu8zos+gd5/PZWXNVrpt4=,tag:9a9+fk6MXbXE7ZtS4/Ogow==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:X/0foZAGKcpnDYebGnVh9i47xiHvV44x4vYfBVkcQE4=,iv:15LAsRl6dpgszaegD3qKMVA+FNcrEox/xd2WnVS1bro=,tag:hjulSnKs5VJ6c8M0+A4ttQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:BMDxJ1auybvO6N8mFe2/VNDlOPw=,iv:O0HUMk6v/rvAn3mQYm5F8zpmXpdLSnFvK2sSTWo4M4Y=,tag:mWUmyIC/A84Y+NfBptGezw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1E4ckVMSDdnUzZWVzgw
            NHVpWTVaNGxGZVRUSW04N1B1V0E3THpDZWo4ClE3QVFDMGZQVm9kcm1HU3lldDhU
            bkRMNVFwbUZaVTFQT1YrM21UTUVBK2MKLS0tIFM5YTBRa3V1R2tNVnRoQ2gvVzk5
            UWJoVjV6bkUxM3dNNU9BREZMeGtCRTgKIqoRQLlZ+KS4/SLVkcCfmWv/5mKjX7Fb
            iKQGZuuJtfrQ238GaecEZn9rN2F3vm1SogKdtwduBmdQysYN8g4Kug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T23:08:15Z"
    mac: ENC[AES256_GCM,data:EeJHB2mHUE7CbX13IuSlUMfcK3mTQVofTsltd1lGXkGIdLhUwBtcsZ9Kfn5SxIpFSd3fna3cy93aKXjJ6e3B0MJ+ols/8LFRyB6PB0x5l7qQuf8AhK2Br41rhE6puEi7HrFk4UHIY7/HWtQ60cIsB+X0QeppEfC2zuESRjiLP3A=,iv:z0ADVCr4YFIMWHJ5GpQCtSJ4YHNOXN6NM0WyKuMs0uk=,tag:pKdzkEP7GHHNa1ANri4C3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
