---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs-system
helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    version: 4.2.0
    releaseName: openebs
    valuesFile: values.yaml
    includeCRDs: true
