---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: toolhive-secret
    creationPolicy: Owner
  data:
    - secretKey: HA_TOKEN
      remoteRef:
        key: /ai/toolhive/HA_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: /ai/toolhive/GRAFANA_SERVICE_ACCOUNT_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
