---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: eaton-ups
spec:
  rules:
    - # MGE UPS Systems UPS (Eaton UPS)
      name: mge-ups
      labels:
        mge.feature.node.kubernetes.io/ups: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["03"] }
            vendor: { op: In, value: ["0463"] }
            device: { op: In, value: ["ffff"] }
