apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: runner-scale-set-listener
  namespace: actions
  labels:
    app.kubernetes.io/component: runner-scale-set-listener
spec:
  jobLabel: runner-scale-set-listener
  namespaceSelector:
    matchNames:
    - actions
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: runner-scale-set-listener
