runnerScaleSetName: default
githubConfigUrl: https://github.com/swibrow/home-ops
githubConfigSecret: actions-runner-controller-auth
minRunners: 0
maxRunners: 10
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes:
      - ReadWriteOnce
    storageClassName: openebs-hostpath
    resources:
      requests:
        storage: 5Gi
  kubernetesModeServiceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::633355703129:role/pitower
controllerServiceAccount:
  namespace: actions
  name: actions-runner-controller
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/onedr0p/actions-runner:2.322.0
        command:
          - /home/runner/run.sh
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        volumeMounts:
          - mountPath: /var/run/secrets/talos.dev
            name: talos
            readOnly: true
    serviceAccountName: actions-runner
