---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - configmap.yaml
  - externalsecret.yaml
components:
  - ../../../../components/volsync
configMapGenerator:
  - name: volsync-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=frigate
      - CLAIM_NAME=frigate
      - SECRET_NAME=frigate-volsync
      - STORAGE_SIZE=5Gi
      - RESTIC_REPO=s3:https://s3.eu-central-2.amazonaws.com/pitower-volsync-backups/home-automation/frigate
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 5.0.1
    releaseName: frigate
    namespace: home-automation
    valuesFile: values.yaml
