controllers:
  frigate:
    strategy: Recreate
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: "worker-04"
      tolerations:
        - key: dedicated
          operator: Equal
          value: media-home
          effect: NoSchedule
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups: [44, 109]
    containers:
      app:
        image:
          repository: ghcr.io/blakeblackshear/frigate
          tag: 0.17.1
        envFrom:
          - secretRef:
              name: frigate-secret
        env:
          TZ: Europe/Zurich
          LIBVA_DRIVER_NAME: iHD
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/version
                port: 5000
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/version
                port: 5000
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
        resources:
          requests:
            cpu: 791m
            gpu.intel.com/i915: 1
            memory: 2672Mi
          limits:
            gpu.intel.com/i915: 1
            memory: 4Gi

service:
  app:
    controller: frigate
    ports:
      http:
        port: 5000
      rtsp:
        port: 8554
        protocol: TCP
      webrtc-tcp:
        port: 8555
        protocol: TCP
  webrtc-udp:
    controller: frigate
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 10.20.10.235
    ports:
      webrtc-udp:
        port: 8555
        protocol: UDP

route:
  app:
    hostnames:
      - frigate.wibrow.dev
    parentRefs:
      - name: envoy-internal
        namespace: networking
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 5000

persistence:
  config:
    existingClaim: frigate
    advancedMounts:
      frigate:
        app:
          - path: /config
  config-file:
    type: configMap
    name: frigate-config
    advancedMounts:
      frigate:
        app:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
  media:
    type: nfs
    server: data
    path: /volume1/cctv
    advancedMounts:
      frigate:
        app:
          - path: /media/frigate
  cache:
    type: emptyDir
    advancedMounts:
      frigate:
        app:
          - path: /tmp/cache
  shm:
    type: emptyDir
    medium: Memory
    sizeLimit: 1Gi
    advancedMounts:
      frigate:
        app:
          - path: /dev/shm
