---
# https://github.com/authelia/authelia/blob/master/config.template.yml
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
log:
  level: 'debug'

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 1m
  ldap:
    address: ldap://lldap.security.svc.cluster.local:5389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=pitower,dc=link
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: "$${LLDAP_BIND_USER_DN}"
    password: "$${LLDAP_BIND_PASSWORD}"
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn

session:
  secret: "{{ .authelia_session_secret }}"
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: pitower_link_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}

storage:
  encryption_key: "{{ .authelia_storage_encryption_key }}"
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: true
  smtp:
    address: aspmx.l.google.com.:25
    sender: Authelia <authelia@${SECRET_DOMAIN}>
    disable_require_tls: true

duo_api:
  disable: true

access_control:
  default_policy: one_factor
  rules:
    - domain:
        - actual.${SECRET_DOMAIN}
      subject:
        - ["group:auth_users"]
      policy: one_factor
    - domain:
        - jellyfin.${SECRET_DOMAIN}
      subject:
        - ["group:auth_users"]
      policy: one_factor

identity_validation:
  reset_password:
    jwt_secret: "{{ .authelia_jwt_secret }}"
    jwt_lifespan: '5 minutes'
    jwt_algorithm: 'HS256'

# https://www.authelia.com/configuration/identity-providers/openid-connect/provider/
identity_providers:
  oidc:
    hmac_secret: "{{ .authelia_oidc_hmac_secret }}"
    jwks:
      - key: |-
          {{- .encoded_authelia_oidc_issuer_key | nindent 10 }}
        algorithm: 'RS256'
    clients:
      - client_id: "{{ .authelia_jelly_id }}"
        client_name: 'Jellyfin'
        client_secret: "{{ .authelia_jelly_secret }}"
        public: false
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://jellyfin.${SECRET_DOMAIN}/sso/OID/redirect/authelia'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
        userinfo_signed_response_alg: 'none'
        # token_endpoint_auth_method: 'client_secret_post'

      - client_id: grafana
        client_name: 'Grafana'
        client_secret: "{{ .authelia_grafana_secret }}"
        public: false
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://grafana.${SECRET_DOMAIN}/login/generic_oauth'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
        # token_endpoint_auth_method: 'client_secret_basic'
