localpv-provisioner:
  rbac:
    create: true
  localpv:
    image:
      registry: quay.io/
      repository: openebs/provisioner-localpv
    basePath: /var/mnt/extra/openebs/local
  hostpathClass:
    enabled: true
    name: openebs-hostpath
    isDefaultClass: false
    basePath: /var/mnt/extra/openebs/local

openebs-crds:
  csi:
    volumeSnapshots:
      enabled: false
      keep: false

zfs-localpv:
  enabled: false

lvm-localpv:
  enabled: false

mayastor:
  enabled: false

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false
