---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking
resources:
  - ./externalsecret.yaml
components:
  - ../../../../components/volsync
  - ../../../../components/cnpg-db
configMapGenerator:
  - name: cnpg-db-config
    literals:
      - APP_NAME=paperless
      - SECRET_NAME=paperless-db-secrets
      - CNPG_SECRET_KEY=paperless-app
  - name: volsync-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=paperless
      - CLAIM_NAME=paperless-data
      - SECRET_NAME=paperless-volsync
      - STORAGE_SIZE=5Gi
      - RESTIC_REPO=s3:https://s3.eu-central-2.amazonaws.com/pitower-volsync-backups/banking/paperless
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 4.6.2
    releaseName: paperless
    namespace: banking
    valuesFile: values.yaml
