---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
helmCharts:
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: v1.17.3
    releaseName: rook-ceph-cluster
    valuesFile: values.yaml
