---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./aws-identity-webhook.yaml
commonLabels:
  app.kubernetes.io/name: aws-identity-webhook
  app.kubernetes.io/instance: aws-identity-webhook
