---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.6.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 3
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: s3
          schema: v13
      storage:
        type: 's3'
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki
        s3:
          endpoint: rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local
          s3ForcePathStyle: true
          insecure: true

    singleBinary:
      replicas: 3
      extraEnvFrom:
        - secretRef:
            name: loki-bucket
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 20Gi

    chunksCache:
      enabled: false

    resultsCache:
      enabled: false

    lokiCanary:
      enabled: false

    test:
      enabled: false

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
