controllers:
  readarr:
    annotations:
      secret.reloader.stakater.com/reload: readarr-secret
    pod:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
    containers:
      app:
        image:
          repository: ghcr.io/onedr0p/readarr-develop
          tag: "0.3.32"
        env:
          READARR__INSTANCE_NAME: Readarr
          READARR__PORT: &port 8787
          READARR__APPLICATION_URL: "https://readarr.pitower.link"
          READARR__LOG_LEVEL: info
          READARR__API_KEY:
            valueFrom:
              secretKeyRef:
                name: readarr-secret
                key: api_key
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 5m
            memory: 224M
          limits:
            memory: 224M
service:
  app:
    controller: readarr
    ports:
      http:
        port: *port

ingress:
  app:
    className: internal
    hosts:
      - host: readarr.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http
persistence:
  config:
    existingClaim: readarr-config
  media:
    type: nfs
    server: data
    path: /volume1/media
    globalMounts:
      - path: /data/nas-media
