---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/pitower/apps/actions/actions-runner-controller/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller-runners
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/pitower/apps/actions/actions-runner-controller/runners"
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  dependsOn:
    - name: actions-runner-controller
