---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn
resources:
  - wireguard.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: wg-configmap
    files:
      - wg0.conf
