---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - externalsecret.yaml

configMapGenerator:
  - name: grafana-dashboards-home-assistant
    files:
      - dashboards/home-assistant-overview.json
      - dashboards/home-assistant-sensors.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: HomeAssistant
  - name: grafana-dashboards-envoy
    files:
      - dashboards/envoy-gateway-global.json
      - dashboards/envoy-proxy-global.json
      - dashboards/envoy-clusters.json
      - dashboards/envoy-access-logs.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Envoy
  - name: grafana-dashboards-nodes
    files:
      - dashboards/worker-01-fabric-watch.json
      - dashboards/spegel.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Infrastructure
  - name: grafana-dashboards-networking
    files:
      - dashboards/external-dns.json
      - dashboards/cilium-operator.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Networking

helmCharts:
  - name: grafana
    repo: https://grafana-community.github.io/helm-charts
    version: 12.4.5
    releaseName: grafana
    namespace: monitoring
    valuesFile: values.yaml
