---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - args:
          - --config-file
          - .yamllint.yaml
        id: yamllint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform-fmt
        args:
          - --args=-recursive
      - id: terraform-validate
      - id: tflint