---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    # -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.35.1
  #   hooks:
  #     - id: yamllint
        # args:
        #   - --config-file
        #   - .yamllint.yaml

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.3
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/siderolabs/conform
    rev: v0.1.0-alpha.30
    hooks:
      - id: conform
        stages:
          - commit-msg
