[tools]
talosctl = "1.14.1"
kubectl = "1.37.1"
kustomize = "5.8.1"
helm = "4.3.0"
sops = "3.13.3"
jq = "1.8.2"

[env]
MEMINI_NAMESPACE = "home-ops"
KUBECONFIG = "{{env.HOME}}/.kube/pitower.yaml"
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/mise/age.txt"
INFISICAL_DOMAIN = "https://eu.infisical.com"
INFISICAL_PROJECT_ID = "b2d042d3-0cd8-4bc4-b8c3-66b3f9616a4b"
AGENTGATEWAY_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZFY3NUJkbGI1b3djUm9mdytyK1RWZFFReTExNWRpSHN5ZFJzemtSU2xRCmFQVUx4Y1o2K1pVM3JCeWJBZDJ0azZqNkdKOWwrUUJZL2J4cXVDY1dIQUEKLT4gc3NoLWVkMjU1MTkgOUZ5OUFRIFEwRWJlRjQ4RnRQdzRyTnRKMmpvcVJrWXgvdkZRMGNldHZPY1VJQ2I3UVkKa0pJOVg4eHB5Zmd4Z1ErZCt6bGJJQ3lFbmF0cU8wZmU5d01qaW1tRkdqRQotPiAmL2hWMC1ncmVhc2UgR3dyQyA5SzogT19MCjdrK09pVnBlY3lHSEY1emYKLS0tIDNhZlplaHlyK3hnME1Da3c1QmJwb3FOY1d6YlpuR0lUcWNVcVRGVjhmR3MKfxSeQCVPF1B9BvQ3YfZUxXLxYEs37iG32FenSE1VhbQxSH8bitFv0CpLgAatMywTRKUHq3f0Kt5CNDC6f5crt54ylfusHaSSgllUIniUtPGN5uEHG3m4" }

#ANTHROPIC_MODEL = "claude-opus"
#ANTHROPIC_BASE_URL = "https://litellm.wibrow.dev"
