[tools]
talosctl = "1.13.8"
kubectl = "1.36.3"
kustomize = "5.8.1"
helm = "4.2.4"
sops = "3.13.3"
jq = "1.8.2"

[env]
MEMINI_NAMESPACE = "home-ops"

#ANTHROPIC_MODEL = "claude-opus"
#ANTHROPIC_BASE_URL = "https://litellm.wibrow.dev"
