[tools]
talosctl = "1.14.2"
kubectl = "1.37.1"
kustomize = "5.8.3"
helm = "4.3.0"
sops = "3.13.3"
jq = "1.8.2"
vcluster = "0.37.3"

[env]
MEMINI_NAMESPACE = "home-ops"
KUBECONFIG = "{{env.HOME}}/.kube/pitower.yaml"
SOPS_AGE_KEY_FILE = "{{env.HOME}}/.config/mise/age.txt"
INFISICAL_DOMAIN = "https://eu.infisical.com"
INFISICAL_PROJECT_ID = "b2d042d3-0cd8-4bc4-b8c3-66b3f9616a4b"
AGENTGATEWAY_API_KEY = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZFY3NUJkbGI1b3djUm9mdytyK1RWZFFReTExNWRpSHN5ZFJzemtSU2xRCmFQVUx4Y1o2K1pVM3JCeWJBZDJ0azZqNkdKOWwrUUJZL2J4cXVDY1dIQUEKLT4gc3NoLWVkMjU1MTkgOUZ5OUFRIFEwRWJlRjQ4RnRQdzRyTnRKMmpvcVJrWXgvdkZRMGNldHZPY1VJQ2I3UVkKa0pJOVg4eHB5Zmd4Z1ErZCt6bGJJQ3lFbmF0cU8wZmU5d01qaW1tRkdqRQotPiAmL2hWMC1ncmVhc2UgR3dyQyA5SzogT19MCjdrK09pVnBlY3lHSEY1emYKLS0tIDNhZlplaHlyK3hnME1Da3c1QmJwb3FOY1d6YlpuR0lUcWNVcVRGVjhmR3MKfxSeQCVPF1B9BvQ3YfZUxXLxYEs37iG32FenSE1VhbQxSH8bitFv0CpLgAatMywTRKUHq3f0Kt5CNDC6f5crt54ylfusHaSSgllUIniUtPGN5uEHG3m4" }
# iDRAC8 on proxmox-01/worker-07 (R630), untagged LAN.
IDRAC_HOST = "192.168.0.126"
IDRAC_USERNAME = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N2VGeWFsTlFQZDQ4K2I5N1gvTlRnUHhPNU1tOXl2MVc1MzYrZ1NOU1dFCjRNTzlIdGcrYkx6S2VtK0JIMFhJVWlabFBiaU5wV0MzUHg4Rld0ZUVKQm8KLT4gc3NoLWVkMjU1MTkgOUZ5OUFRIHI4VnRWUC9BR2YwVU54U2hPOXloblZFWXdNcWU1T2dPNG9CY1lXdEdEaUkKTE1mMTZZS3AxelBCKzdRSFVKSXVzb3RZamVOc2lqK0ozTXdES0YreUt4MAotPiA9MDtGVy1ncmVhc2UgcXt2Cm9rZnNMZHNlVHRoemorOW41aTVpWVNKWHQ4Sm9lbFl3WXpveHlCY0pCMzNiSVZTdmhHVEdvNEN1YnMwRHNsVzAKekI2QUxhRWhkVHppUHcKLS0tIDlabnNHTFBZNjVuVHFlSTlUakRaS0drbzF4ZG00aGV1TzVKWkVwNlBXcGsKaqI5Yi36KFmw3d2wjDxGOKIL5U9IV5a8bLPL5XWYNf8DsAX7ag" }
IDRAC_PASSWORD = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVBVK3g4N0tFRUJVMkZFQVJkUk9MdEZLWTkwbnpqK1ZhejV4M2NGQmtFCmh1Q2V1dk54eTRWNTVpTEpzTWFjRkRXdWUxamtFWmNGSG9mKzdaUy9qaUUKLT4gc3NoLWVkMjU1MTkgOUZ5OUFRIENVV0pwZy9NRW9FdlRBaHBySFB4US9lVUtYSzZjOHZrd3dHQkFpRm1zREUKVFJLSEpnaTFyTzdFcWZMdmg3QndrblVzdHM5Mk8yUTdFNVRTSk8yNEVvMAotPiApLmYqdEUtZ3JlYXNlIEcye3JWLy1dIFV6NCBIP3YgXAoxU05vdm1jYk5Rd1ZRS1h6QzlzRzRnWTJ6WmdaeDl5T2QxOTdoRDlRNHQwWm9wMndJdwotLS0gUHhJaENpck1kSHd5dE05TWtzeS9RNUE2MzZnOVJIRFZrL2VBQS8rUURxbwqN8giQdWQxEx3Kv3y/DyfMvSpZ2d/Mgfix2lIaNRnti+V0Pfnan+hn" }

#ANTHROPIC_MODEL = "claude-opus"
#ANTHROPIC_BASE_URL = "https://llm.wibrow.dev"
