---
version: "3"

includes:
  gh:
    taskfile: .taskfiles/gh
    dir: .taskfiles/gh
  k8s:
    taskfile: .taskfiles/k8s
    dir: .taskfiles/k8s
  tf:
    taskfile: .taskfiles/terraform
    dir: .taskfiles/terraform

  talos:
    taskfile: pitower/talos
    dir: pitower/talos
  kubernetes:
    taskfile: pitower/kubernetes
    dir: pitower/kubernetes


env:
  TERRAFORM_WORKING_DIR: "terraform"
  ENVIRONMENT: "dev"

tasks:
  pre-commit:init:
    desc: Initiate and install dependencies
    cmds:
      - pre-commit install

  pre-commit:check:
    desc: Check all pre-commit hooks
    cmds:
      - pre-commit run -a

  secret:ls:
    desc: List all secret files
    silent: true
    cmds:
      - echo "{{.SECRET_FILES}}"
  secret:encrypt:
    desc: Encrypt all secret files
    silent: true
    cmds:
      - echo "{{.SECRET_FILES}}" | xargs  -I {} sops -e -i {}

  gh:all:
    desc: Run all GitHub tasks
    cmds:
      - task gh:repo
      - task gh:update-environment-variables ENVIROMENT=dev
