---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghostfolio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: ghostfolio-secrets
  data:
    - secretKey: ACCESS_TOKEN_SALT
      remoteRef:
        key: /banking/ghostfolio/ACCESS_TOKEN_SALT
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /banking/ghostfolio/JWT_SECRET_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /banking/ghostfolio/REDIS_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
