---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      firefly:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: fireflyiii/core
              tag: version-6.1.25
            resources:
              requests:
                cpu: 15m
                memory: 128Mi
            envFrom:
              - secretRef:
                  name: firefly-secret
              - secretRef:
                  name: firefly-db-secrets
            env:
              TZ: ${TIMEZONE}
              TRUSTED_PROXIES: "**"
              MAIL_MAILER: log
              MAIL_HOST: smtp-relay.gmail.com
              MAIL_PORT: 587
              ALLOW_WEBHOOKS: 'true'
          cronjob:
            image:
              repository: alpine
              tag: 3.21.3
              pullPolicy: IfNotPresent
            command:
              - sh
            args:
              - -c
              - >-
                echo "0 17 * * * wget -qO- http://firefly-iii:8080/api/v1/cron/$(STATIC_CRON_TOKEN)"
                | crontab -
                && crond -f -L /dev/stdout
            env:
              - name: STATIC_CRON_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: firefly-secret
                    key: STATIC_CRON_TOKEN
    service:
      app:
        controller: firefly
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
        hosts:
          - host: &host money.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: firefly-data
        advancedMounts:
          firefly:
            app:
              - path: /var/www/html/storage/upload
