# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: firefly-secret
    labels:
        app.kubernetes.io/name: firefly
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:stmny5FsplUdTH80n1OVHHLyy7hIR4+RWg3d+jcwdUw=,iv:fi1X8WX6NVXIaJ9N6kV+o7Gu8zos+gd5/PZWXNVrpt4=,tag:9a9+fk6MXbXE7ZtS4/Ogow==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:X/0foZAGKcpnDYebGnVh9i47xiHvV44x4vYfBVkcQE4=,iv:15LAsRl6dpgszaegD3qKMVA+FNcrEox/xd2WnVS1bro=,tag:hjulSnKs5VJ6c8M0+A4ttQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:BMDxJ1auybvO6N8mFe2/VNDlOPw=,iv:O0HUMk6v/rvAn3mQYm5F8zpmXpdLSnFvK2sSTWo4M4Y=,tag:mWUmyIC/A84Y+NfBptGezw==,type:str]
    ACCESS_TOKEN: ENC[AES256_GCM,data:+g3jKWthI0pe4S33HeXU6SwD86xjbAYevHT9yNUoIPc8zCgI0Lkcx+zF6d+5UBBO86cgzFGKQSAF7JSBHd5qHlV3QB8RDMV/ICaLXyqBLwcN/ENa8KIyK0cGBhwmZvCFbgpTp7TLOUxL7vP8E5a1W0FtYLjYtl8nYMwyzA9iAxMHG6pLGQ9JzPtFMNLrMID3YNaQv83qNpbBkFv25R7nXJmBGCtlX/1qsvdwCsq6PAbI4ceODlAyKVAdPc0v0xXIfXz1NhoZODCBZ+kvZuLOPsFEivEj9Uk3jWpUtIFC8RMFEN38ldDC1uGkdyv8Wy4ueG/Jzf+qm+xZQGSZiJefU/9f++VwvEDmzzrGD9AT0P2gP1wkIzmeJqFIEi1k4Cdu4VJXvYaFVL1Uoev86+N+iGgS7tkIbKz1Obs2WxHw/sQdwrXDWkGvvp6YkrH4xYumIY8LFc7ztJYIYQJeH6XCbAs3F9i2cerxT5unFyUWa9gMXnk+MX6sbdga8uNnQKf4e3Ng0bzDlqBxyyVtHgm9dCrWrNusJbMecevGfLkc2DIg8O4V762sUOkgKxzFLT12fBzDJU+xm5Xsq4oWuwgTNudOhWqfZwbj75VN8BJB9paoCaPAa0ndfxlHm0UJWdWiEFAL4+ylKVsqLMtf5kuyguiiHoPom9+liprX/yb3E75VTCD1AnxbajT2QdsYAoriX0HAIT/2/hzJd3fk3+0faM3uI+cxzICPVjzbVK3MbA6eu0Lsb4xDnMD6Cf6CjSnXzOHQuCBmneheC+GS0uwVRCK/loE8BsE9OpaAxoeSqVYO01D0ulgH7wXp8N+vUutma5R3fJIJIsGbSOBWwIGgNXwljFED7PFsfFz0JgMgXEZxYE3wzJlCuQxnHXu7lIVvt+CqXb8JyB+yoeKbMIgXKDwEKq9sMab3lP9yAbOtuPFG0CxLHVZXgxWu28qr8vNffoFlSqYycdc0CTqfztdp2+PrvCOJqAqBfLU6KI+yCK1+NHIiuW2FLBW7qppGPARRpvlS3zhZxrqq3pusV+9Wg5VisXy3uq+shfxU9WtDzzfGxl0t3mJOuC7HcokVFWLObiaAqLQ3Oc+4lP3Hg51R1qXIl7ukL6HrwVuhC1Fr6N8/ebT3UAmlgbmDs1IVW/4Tk7K7PfEXHL6ao5gNPKM0cJzugFx/5h8CglDUZ8aFX3AeOvdnamSmuQdae3e1i1lBNeKRz2ZxO1EzdQKW8Fv96i3nB45pxtgsgyWI3gXwOFNcQ3LB2AeLk1NHL67QSAXec4atfV+1xFarDW1V2ERWRwSXtN4=,iv:plJBC6o72PVQrxlkO37lgVZlmWOanbQY1qKqHi8TL2I=,tag:YBT0yDRg2ia4gq6h19sl9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1E4ckVMSDdnUzZWVzgw
            NHVpWTVaNGxGZVRUSW04N1B1V0E3THpDZWo4ClE3QVFDMGZQVm9kcm1HU3lldDhU
            bkRMNVFwbUZaVTFQT1YrM21UTUVBK2MKLS0tIFM5YTBRa3V1R2tNVnRoQ2gvVzk5
            UWJoVjV6bkUxM3dNNU9BREZMeGtCRTgKIqoRQLlZ+KS4/SLVkcCfmWv/5mKjX7Fb
            iKQGZuuJtfrQ238GaecEZn9rN2F3vm1SogKdtwduBmdQysYN8g4Kug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T14:39:27Z"
    mac: ENC[AES256_GCM,data:kYLKuukBFKTkrQY7MWO0S7Zmg6sRi6stMCWXdU6OjaNmGxNx9Wh9BQ8JRACLhIOhC93qFmlROvPj99ArdW2dD2/2bSLJLdUW+GN6YvxvA8gy+M95ixyRDbRm8zsaUhhrJfCj9l55/9OB4Lkg3x6bUXZfrkm9FeZSwhV3u7YSHg8=,iv:10q7bkFnZB097ePH/X8mmLbue/NCH148tzJ72cCHwhc=,tag:THcZJhIRhdK7Cdo41h3yNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
