---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: couchdb-secret
    template:
      engineVersion: v2
      data:
        COUCHDB_USER: "{{ .username }}"
        COUCHDB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: /second-brain/couchdb/COUCHDB_USER
    - secretKey: password
      remoteRef:
        key: /second-brain/couchdb/COUCHDB_PASSWORD
