---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kedacore/http-add-on/main/config/crd/bases/http.keda.sh_interceptorroutes.yaml
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: echo-server
spec:
  target:
    service: echo-server
    port: 8080
  rules:
    - hosts:
        - echo.wibrow.dev
  scalingMetric:
    concurrency:
      targetValue: 100
  timeouts:
    readiness: 30s
