---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
components:
  - ../../../../components/volsync
configMapGenerator:
  - name: volsync-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=zigbee2mqtt
      - CLAIM_NAME=zigbee2mqtt
      - SECRET_NAME=zigbee2mqtt-volsync
      - STORAGE_SIZE=1Gi
      - RESTIC_REPO=s3:https://s3.eu-central-2.amazonaws.com/pitower-volsync-backups/home-automation/zigbee2mqtt
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 4.6.2
    releaseName: zigbee2mqtt
    namespace: home-automation
    valuesFile: values.yaml
