---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - href: https://youtube.com/feed/subscriptions
    - Tech:
        - HackerNews:
            - href: https://news.ycombinator.com
        - Moronix:
            - href: https://www.phoronix.com
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  services.yaml: |
    - Calendar:
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 20 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Radarr # service name for that widget
    - Automation:
        - Home Assistant:
            href: https://ha.pitower.link
            icon: home-assistant.svg
            widget:
              type: homeassistant
              url: http://ha.pitower.link:8123
              key: {{HOMEPAGE_VAR_HASS_TOKEN}}
    - Infrastructure:
        - Unifi:
            href: https://unifi.pitower.link
            icon: unifi.png
            widget:
              type: unifi
              url: https://unifi.pitower.link
              key: {{HOMEPAGE_VAR_UNIFI_TOKEN}}
  settings.yaml: |
    title: Dashboard
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Calendar:
        style: columns
      Automation:
        style: columns
      Selfhosted:
        style: row
        columns: 2
      Downloads:
        style: row
        columns: 3
      Games:
        style: row
      Infrastructure:
        style: row
        columns: 2
      Monitoring:
        style: row
        columns: 3
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: [google]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
