---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
      version: 4.0.1
  maxHistory: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.2.0
            env:
              TZ: ${TIMEZONE}
              HOMEPAGE_ALLOWED_HOSTS: home.pitower.link
              # LOG_LEVEL: debug
            # envFrom:
            #   - secretRef:
            #       name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 3000
                    path: /api/healthcheck
                    httpHeaders:
                      - name: Host
                        value: home.pitower.link
                  initialDelaySeconds: 0
              readiness: *probes
              startup: *probes
        serviceAccount:
          identifier: homepage
    service:
      app:
        controller: homepage
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.pitower.link
          # authentik.home.arpa/enabled: "true"
          # nginx.ingress.kubernetes.io/auth-signin: |-
          #   https://${HOSTNAME}/outpost.goauthentik.io/start?rd=$escaped_request_uri
        hosts:
          - host: home.pitower.link
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      homepage: {}
