---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cnpg-secrets
    kind: ClusterSecretStore
  target:
    name: firefly-db-secrets
    template:
      type: Opaque
      data:
        DB_CONNECTION: pgsql
        DB_cloudnative-pg: firefly
        DB_HOST: '{{ index . "host" }}.cloudnative-pg.svc.cluster.local'
        DB_PORT: '{{ index . "port" }}'
        DB_USERNAME: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: firefly-superuser
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: firefly-secrets

  # dataFrom will fetch all secrets that are inside the `secretsPath`. When `recursive` is
  # enabled, it will also fetch all secrets recursively in sub-directories.
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: /banking/firefly/APP_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: MAIL_FROM
      remoteRef:
        key: /banking/firefly/MAIL_FROM
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: STATIC_CRON_TOKEN
      remoteRef:
        key: /banking/firefly/STATIC_CRON_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None