---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firefly
  namespace: flux-system
spec:
  path: "./pitower/kubernetes/apps/banking/firefly/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  interval: 30m
  wait: false
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: rook-ceph-cluster
