---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./pihole.yaml
  - ./plex.yaml
  - ./postgres-operator.yaml
  - ./postgres-operator-ui.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./swibrow.yaml
  - ./uptime-kuma.yaml
  - ./cloudnative-pg.yaml
  - ./actions-runner-controller.yaml
  - ./external-secrets.yaml
  - ./intel.yaml
  - ./node-feature-discovery.yaml
  - ./rook-ceph.yaml
  - ./piraeus.yaml
  - ./backube.yaml
  - ./1password.yaml
  - ./postfinance.yaml
  - ./kubernetes-sigs-metrics-server.yaml
