# de94b242ed9adec9def2581ffbf1e2d1873e42b17032771770d241dee54d7c00
# curl -X POST --data-binary @rpi-poe.yaml https://factory.talos.dev/schematics
overlay:
  image: siderolabs/sbc-raspberrypi
  name: rpi_generic
  options:
    configTxtAppend: |-
      # PoE Hat Fan Speeds
      dtoverlay=rpi-poe
      dtparam=poe_fan_temp0=50000
      dtparam=poe_fan_temp1=60000
      dtparam=poe_fan_temp2=70000
      dtparam=poe_fan_temp3=80000
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/util-linux-tools
