---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./udproute.yaml
components:
  - ../../../components/volsync
configMapGenerator:
  - name: volsync-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=sharkord
      - CLAIM_NAME=sharkord
      - SECRET_NAME=sharkord-volsync
      - STORAGE_SIZE=1Gi
      - RESTIC_REPO=s3:https://s3.eu-central-2.amazonaws.com/pitower-volsync-backups/selfhosted/sharkord
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 4.6.2
    releaseName: sharkord
    namespace: selfhosted
    valuesFile: values.yaml
