---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bar-assistant-meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
