---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc
components:
  - ../../../../components/arc-runner
configMapGenerator:
  - name: arc-runner-config
    literals:
      - SERVICE_ACCOUNT=homb-runners
generatorOptions:
  disableNameSuffixHash: true
helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: homb-runners
    namespace: arc
    valuesFile: values.yaml
