---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
commonLabels:
  app.kubernetes.io/name: 1password-connect
  app.kubernetes.io/instance: 1password-connect
