image:
  repository: ghcr.io/rook/ceph
crds:
  enabled: true
csi:
  enableCephfsDriver: false
  pluginTolerations:
    - key: dedicated
      operator: Equal
      value: media-home
      effect: NoSchedule
    - key: dedicated
      operator: Equal
      value: storage
      effect: NoSchedule
    - key: node-issue
      operator: Equal
      value: "true"
      effect: NoExecute
monitoring:
  enabled: false
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits: {}
