---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: autobrr
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: autobrr
      owner: autobrr
  storage:
    size: 1Gi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  storage:
    size: 1Gi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: house-hunter
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: house_hunter
      owner: house_hunter
  storage:
    size: 1Gi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lldap
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: lldap
      owner: lldap
  storage:
    size: 100Mi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefly
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: firefly
      owner: firefly
  storage:
    size: 100Mi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
  storage:
    size: 100Mi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
  storage:
    size: 1Gi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ghostfolio
  namespace: cloudnative-pg
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: ghostfolio
      owner: ghostfolio
  storage:
    size: 100Mi
    storageClass: openebs-hostpath
  monitoring:
    enablePodMonitor: true
