apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
stringData:
    token: ENC[AES256_GCM,data:/3FsgzDEiAXKdBS0AafkaYnEXGvfTplnC9XUhLxdJjVIq85+sELzc9X8jWKVpAG+vfEIVSlvOOdT+pgNf+XVeBmwlRSR3JkrdS0OfES6uLDxM3sEGoR3u/ii17QIkUQlyYGIsQXOThqJBC+oBDRJ43M/PZFhj2ypJC4Poy3IcfpxaDLKjVxw0+ANiKM+ztShrehPfP1RJdpsSy9JSa2swsZTBSKGIUzO0GDlpigUM/mfVE7bdBYZEY1WLpin1K8PTJjGatwPs/5Nfr6qF2V1fg7BFMHbguisgoqE2DeHM2i9/ABeTEZKv64HzNGd0Z0t8j6DWIa0qvdezM1v9sw/kNHJhHjU0vslLifjpZzCpIRchUslY6PzpKv1DJgyLaWkn8wY2fte4xxeGStcsNc6o+3zXbSEeW2LAjqFutWNucKef4CWZiwixxYU+ubMPDJIKBm8kV1aLOssyf+OkCpL1jueXjfSxmwnS9JzfYf2+9zWCpDzGyROLHuqIIbqTC9B5U3Bp+HZBIrko6iEYJH8HNTM//OnLoLuqhlFpX0OL9MqiBqS/6cILTE5y+B6uUZMA5/AHiUhK77/R46Fs9jzQZ7aFaFPOcg2eUZnMK15XU+0sxMszcR9jJkCV+fbTdCL3xFbKfVjFPLrCQ7TAqkW8h3OLfwIgSsPIVKbp+YR9Zayk6ImQ40B5Bp+XrFZEtrjrNRWwUhKcpa8lDEHn1kn7dZOdV8SzM4W4vIwovEadn9tcluYsYD83bWdhnoJfB5wI1jYij+wmQTkYPOSva8fpgwgWOSXvAvCjLs09Mt+h1tRRzVmsSzIyyBScT0wwQ0hWKmB6xHbxCcNj+vfRmJmq/xU,iv:IpmDqqmXps3qmJ7ncWYvIU7xAjkzYy1dDKkILTOauIA=,tag:qW5zvzOuRxjb3jmJAf+Nfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ1piY2h0YWdoaGtpNEZB
            QXhhR29mby9zRHE5Z0tyRmFFVFV6TXF3VHlVCmpENUt4MklpRERsOVlxeEY2YW9M
            QWpzQUNzblZWalZoV2hHcE1TOW9vZXMKLS0tIHFtZVd2aktpci9yREVNNTkxR1lS
            UFRkWmw5Y1p6NjNEaHp4L2VXYm5zd1UKBP2oBeOMr1ibTyGR/pypjh9LREV2gwg9
            MmM1DbdmU1bL+RsToOH65SMMQuY8LbA3R2H/Q2feYv8AY6gR3XZe1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T06:53:16Z"
    mac: ENC[AES256_GCM,data:Q7Mi0C/mwS2+Ajvjfi4vnh8nVOOCTlMt8oy0/2yjjWG/CeIoAxQQ+Xkec4XOn9MB3iqUGOdxQOMTkQzUddhmDruaYqGQ16zz9IXUg/BtyM3JYrMUaoLUp66GLxrbMo6K9IQlUaw1Rj8YmLWiDL9rNNCoVPSEUJh/fu6ElM2iPWU=,iv:wVs/mZVQOCUBj3ByWZp8mC5sJ9FZKDo4VMbdl3vGPqA=,tag:GpbyeJyWcJGAeDPCP98vyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
