prometheus:
  enable: true
master:
  # krr: node-feature-discovery-master/master
  resources:
    requests:
      cpu: 10m
      memory: 51Mi
worker:
  tolerations:
    - key: dedicated
      operator: Equal
      value: media-home
      effect: NoSchedule
  config:
    core:
      sources:
        - pci
        - system
        - usb
  # krr: node-feature-discovery-worker/worker
  resources:
    requests:
      cpu: 5m
      memory: 48Mi
