---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: metrics-server
    repo: https://coredns.github.io/helm
    version: 1.42.2
    releaseName: coredns
    namespace: kube-system
    valuesFile: values.yaml
