---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cryptgeon
  namespace: flux-system
spec:
  path: ./kubernetes/pitower/apps/tools/cryptgeon/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
