---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  path: ./pitower/kubernetes/infra/flux-system/weave-gitops/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
