---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./externalsecret.yaml
components:
  - ../../../../components/pvc
  - ../../../../components/kopiur
  - ../../../../components/cnpg-db-shared
configMapGenerator:
  - name: cnpg-db-config
    literals:
      - APP_NAME=open-webui
      - SECRET_NAME=open-webui-db-secret
      - CNPG_SECRET_KEY=ai-open-webui
      - DB_SCHEME=postgresql
  - name: pvc-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=open-webui-pvc
      - CLAIM_NAME=open-webui-data
      - STORAGE_SIZE=10Gi
  - name: kopiur-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=open-webui-kopiur
      - CLAIM_NAME=open-webui-data
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 5.1.0
    releaseName: open-webui
    namespace: ai
    valuesFile: values.yaml
