---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cnpg-secrets
    kind: ClusterSecretStore
  target:
    name: firefly-db-secrets
    template:
      type: Opaque
      data:
        DB_CONNECTION: pgsql
        DB_DATABASE: firefly
        DB_HOST: '{{ index . "host" }}.database.svc.cluster.local'
        DB_PORT: '{{ index . "port" }}'
        DB_USERNAME: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: firefly-superuser
