---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./secret.sops.yaml
commonLabels:
  app.kubernetes.io/name: firefly
  app.kubernetes.io/instance: firefly

