# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: firefly-secret
    labels:
        app.kubernetes.io/name: firefly
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:YDBtXQ2EOA==,iv:jBqHKdx6D63UQCKjoEnLWn8X7YpcDCG6g5k4+NIAOb0=,tag:iNIBy59X4jOtbbaHX4HOcw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:KUM4djbrb3rbEz5uEWLtzhVFpipNwkQ=,iv:J8L/Fwd/qFajXBxCGXMtv9WxqbPqyuJTDG4QvtGBoUE=,tag:0y/MtoZDiIUvUhv7nEQssg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:HiXuUw1nbblQ3hcvegJeCcTtOjEgda7KYLBAzxlY/no=,iv:doqDL9s+IrAWbp+DzVZxWKEhOCtY9GkmJOgv9GD6C8Y=,tag:8ywJDtKcCk9UH2i7DI3VXg==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:X/0foZAGKcpnDYebGnVh9i47xiHvV44x4vYfBVkcQE4=,iv:15LAsRl6dpgszaegD3qKMVA+FNcrEox/xd2WnVS1bro=,tag:hjulSnKs5VJ6c8M0+A4ttQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:BMDxJ1auybvO6N8mFe2/VNDlOPw=,iv:O0HUMk6v/rvAn3mQYm5F8zpmXpdLSnFvK2sSTWo4M4Y=,tag:mWUmyIC/A84Y+NfBptGezw==,type:str]
    APP_PASSWORD: ENC[AES256_GCM,data:8uf6eCeLlio=,iv:KXfCl+LhfVV4RiRIGNHVLUkE2jtln88fcY0HGIzjCcQ=,tag:xdR27ZknKwcdN+u26pd80A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1E4ckVMSDdnUzZWVzgw
            NHVpWTVaNGxGZVRUSW04N1B1V0E3THpDZWo4ClE3QVFDMGZQVm9kcm1HU3lldDhU
            bkRMNVFwbUZaVTFQT1YrM21UTUVBK2MKLS0tIFM5YTBRa3V1R2tNVnRoQ2gvVzk5
            UWJoVjV6bkUxM3dNNU9BREZMeGtCRTgKIqoRQLlZ+KS4/SLVkcCfmWv/5mKjX7Fb
            iKQGZuuJtfrQ238GaecEZn9rN2F3vm1SogKdtwduBmdQysYN8g4Kug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T01:13:38Z"
    mac: ENC[AES256_GCM,data:OeYP9hZM6XXlkzitflCvd0Gr2SrgP16G+YLPnbtPSRPfkZdtZ4Yifh7jc+w7KSAL3EnOlkojCNFcVdnXi9t2xxoUk/wnvVIUnO5PGY3n32ByQw/Hl0TjiMWI9FEDfE5R2bphvMUipo0B8lZ5+zFRu7YMtJvlYlr9Kq3CS/3k9ds=,iv:V9f3tF/PucWj5f7GyPqqAFIHbw6nlHWlm0q8JRKOiuI=,tag:KtUYwygM8NO/lkxYIetpSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
