# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: firefly-secret
    labels:
        app.kubernetes.io/name: firefly
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:fU579UZk5g4l+yaHgQxvtBCJxK9xiBN31LaH2R2yOD8=,iv:KNwR2rpEc/9rFOlaCawGqbganqHASMZuTvRWvUbRU78=,tag:C29IBqNf2oUiqzM2K3Dtvg==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:X/0foZAGKcpnDYebGnVh9i47xiHvV44x4vYfBVkcQE4=,iv:15LAsRl6dpgszaegD3qKMVA+FNcrEox/xd2WnVS1bro=,tag:hjulSnKs5VJ6c8M0+A4ttQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:BMDxJ1auybvO6N8mFe2/VNDlOPw=,iv:O0HUMk6v/rvAn3mQYm5F8zpmXpdLSnFvK2sSTWo4M4Y=,tag:mWUmyIC/A84Y+NfBptGezw==,type:str]
    APP_PASSWORD: ENC[AES256_GCM,data:8uf6eCeLlio=,iv:KXfCl+LhfVV4RiRIGNHVLUkE2jtln88fcY0HGIzjCcQ=,tag:xdR27ZknKwcdN+u26pd80A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1E4ckVMSDdnUzZWVzgw
            NHVpWTVaNGxGZVRUSW04N1B1V0E3THpDZWo4ClE3QVFDMGZQVm9kcm1HU3lldDhU
            bkRMNVFwbUZaVTFQT1YrM21UTUVBK2MKLS0tIFM5YTBRa3V1R2tNVnRoQ2gvVzk5
            UWJoVjV6bkUxM3dNNU9BREZMeGtCRTgKIqoRQLlZ+KS4/SLVkcCfmWv/5mKjX7Fb
            iKQGZuuJtfrQ238GaecEZn9rN2F3vm1SogKdtwduBmdQysYN8g4Kug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T07:43:30Z"
    mac: ENC[AES256_GCM,data:Y/Ggjy0YKo0/MzyeHxf7/VK8heBadGBLHO99PJDQOqiktVqYla/DdkYAjIDCWehZMzQFVBmt2XGb9/bP0miF1scPADJ+ZTtnNCEoizDUppKysyDsxuX5ZQ6ip5Igr3KQOtzTp92kc+bVp8PjL38v2F4FG4S6/krh8FpLtD2FCE0=,iv:BCOgplP6LJKpY3E4H21L2XQN509yxlVx66DaIcmBSks=,tag:5o/LmMwQ/gJRnda468ZszQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
