---
originRequest:
  http2Origin: true

ingress:
  - hostname: "wibrow.dev"
    service: https://envoy-external.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.wibrow.dev"
  - hostname: "*.wibrow.dev"
    service: https://envoy-external.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.wibrow.dev"
  - hostname: "wibrow.dev"
    service: https://envoy-external.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.wibrow.dev"
  - hostname: "*.wibrow.dev"
    service: https://envoy-external.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.wibrow.dev"
  - service: http_status:404
