---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"ghcr.io":{"username":"swibrow","password":"{{ .token }}","auth":"{{ printf "swibrow:%s" .token | b64enc }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: /dev/propagit/ghcr_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
