defaultPodOptions:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: &app lldap
controllers:
  lldap:
    replicas: 2
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/lldap/lldap
          tag: v0.6.2@sha256:9e605a66c02514bfcffd1b67cafb1e98d50992216bb2871d7ae44622047dd09d
        env:
          TZ: Europe/Zurich
          LLDAP_HTTP_PORT: &port 8080
          LLDAP_HTTP_URL: https://lldap.pitower.link
          LLDAP_LDAP_PORT: &ldapPort 5389
          LLDAP_LDAP_BASE_DN: dc=pitower,dc=link
          LLDAP_KEY_FILE: ""
          # LLDAP_FORCE_LDAP_USER_PASS_RESET: "true" # Uncomment to force password reset
        envFrom:
          - secretRef:
              name: lldap-secret
          - secretRef:
              name: lldap-db
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 128Mi
service:
  app:
    controller: *app
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: lldap.pitower.link
      io.cilium/lb-ipam-ips: "192.168.0.222"
    ports:
      http:
        port: *port
      ldap:
        port: *ldapPort
ingress:
  app:
    className: internal
    hosts:
      - host: &host "{{ .Release.Name }}.pitower.link"
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host

persistence:
  data:
    type: emptyDir
    globalMounts:
      - path: /data
