---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.1.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 100Gi
              storageClass: ceph-filesystem
              globalMounts:
                - path: /config

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          nodeSelector:
            kubernetes.io/arch: amd64
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: "4"
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                sabnzbd.pitower.link
              # SABNZBD__API_KEY:
              #   valueFrom:
              #     secretKeyRef:
              #       name: sabnzbd-secret
              #       key: api_key
              # SABNZBD__NZB_KEY:
              #   valueFrom:
              #     secretKeyRef:
              #       name: sabnzbd-secret
              #       key: nzb_key
            # resources:
            #   requests:
            #     cpu: 5m
            #     memory: "1024M"
            #   limits:
            #     memory: "4096M"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "sabnzbd.pitower.link"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        type: nfs
        server: data
        path: /volume1/media
        globalMounts:
          - path: /data/nas-media
      downloads:
        type: emptyDir
        globalMounts:
          - path: /downloads
