controllers:
  qbittorrent:
    pod:
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      terminationGracePeriodSeconds: 120

    containers:
      app:
        nameOverride: qbittorrent
        image:
          repository: ghcr.io/onedr0p/qbittorrent-beta
          tag: 5.0.3@sha256:4b9de3356475bd97fda3fb4d98f213e8d139aef15e7bd20dab72973e661901dd
        env:
          UMASK: "022"
          QBT_WEBUI_PORT: &port 8080

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 8192Mi
        securityContext:
          runAsUser: 2000
          runAsGroup: 2000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    controller: qbittorrent
    ports:
      http:
        port: *port

ingress:
  app:
    className: internal
    hosts:
      - host: qbittorrent.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http

persistence:
  config:
    enabled: true
    existingClaim: qbittorrent-config
    advancedMounts:
      qbittorrent:
        app:
          - path: /config
  downloads:
    type: nfs
    server: data
    path: /volume1/media
    globalMounts:
      - path: /data/nas-media
        subPath: downloads/qbittorrent
