---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OIDC_JELLYFIN_CLIENT_ID: "{{ .authelia_jelly_id }}"
        OIDC_JELLYFIN_CLIENT_SECRET: "{{ .authelia_jelly_secret }}"

  dataFrom:
    - extract:
        key: authelia
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authelia_$1"
