apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: security
stringData:
    LLDAP_BIND_PASSWORD: ENC[AES256_GCM,data:+vd2+7FQHxA6EBzcSVjUomc8nuUU7VDjYgT30vj3h09nx2Nr7NkTgQ==,iv:Xq/S4VHm6Eqc2dHdopaDOsgKm0KkOCPtmADvDkaxXiQ=,tag:5nIZNz1P4xWEH22npem2/Q==,type:str]
    LLDAP_BIND_USER_DN: ENC[AES256_GCM,data:tEn0OwuK/Y9CH/iolX8Jr+CZN7QnRyg/DQNo4qjfj2xbUyTfWs681Hyn,iv:gb0aB3Cd20faKVV/L/R3Fln1HZHrKMjWszcXov2W9Og=,tag:f2Pl6RUbrrP6g01JDXhDFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdUFzKzk2ZGdheUoyWk43
            WlUza3doYTFqTGw1SkJOb01FZWFUY2RlVjBvCnVqbHVvZjNhaWtWT0FLTkZMWFhv
            dTBkQ3hUZ2dMWVgrdk1pekRKL2dKOG8KLS0tIFgySWZpcDZnSEhKTENNcWs3NVA5
            TWZMcC9aSktKQVE1UXJ3a2ZsU1BPNzAK4TvxMjF3SZG8Mti6pfybZ0kyu+qHNUNk
            PsYWq4ebssdAWf0vLIt7XXDZfBcrFaIjP+907oJq5FR6NyfrTCpu6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T05:42:29Z"
    mac: ENC[AES256_GCM,data:HBfMCiJqirTTaO6Y5GiClpgN4jFnGB1rlVsS1gGQn4kjN2VFXGFcSSG/VGkXZuREUat44LQSSFphJKnYF3tWWMeUvaks3djlrFoJta/pbRPyx+ozTEt6H92x70r5FdafnDmBg44hMa4NagNiTBrC2nyppgxbjsY8C8p0VMxEzVM=,iv:tDy3qQ6C+5xapc2N98emJVjMxQQJ/OPd5rxmcFZwF3s=,tag:RfP2kc+0LZqwjKXs8mxcrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
