apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:KLHCula0afjjWXHC3K58tWZAsavc3mNWNZsVISzK00227QnQXvZgeg==,iv:67HfyDnFXDsfMu7A8adw85ttTx7sE2f8ZNI+VwPwXeA=,tag:Fo3avR5gAI21m4E4Jhy65g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSksxTkUrRTlyaG9veEIy
            OGdMaERVMFFzWXBpbWJjSmgwdEUxLzNxNVJVCjhtbDlrMkFHRFJTd1RFelZVOGVY
            UEpDQmJueWU2VVZCODZaK2FNOXVxSkUKLS0tIHgwck1DNVdxOUVCdWZWUnplQTZx
            dzFVekhuNkFkN1FhaUx1OHBpaG9yWWsKJjJD8GygUVvhmMEiPE3+EODwtQD7BCw4
            7wEpfUDmvf29Z1MtueaBIvABTe9/8GOjq/ZODbqFH10QxmOy1znr8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T07:21:38Z"
    mac: ENC[AES256_GCM,data:1/PCTZ7pz7G4RevSSOpZcWozzcQjkZSlBrIjLYTUnruqXKw1KhOoBzkDiLUXgYJbejGNd6oB7m6Xp+b4WkOFqdD8a893zwKCqH1Vw+B/2737bcnmo3ORF+CON1x7unR8e3FngK3dowWUOAujgdVwvScDvHhSEt9ryn2gRTJuDbc=,iv:2zrjZJ7metewqylaXDCpQAxFqJTf2cCmPbK2ftCn5Zk=,tag:/rz5Y74fIBKUXDL2J18v5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
