---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.30.1
    releaseName: loki
    valuesFile: values.yaml
