---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  namespace: flux-system
  name: pitower
spec:
  interval: 1m
  url: https://github.com/swibrow/pitower
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/pitower/kubernetes
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./pitower/kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: pitower
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: flux
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false