---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: app
spec:
  sourcePVC: app
  trigger:
    schedule: "0 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: app-volsync
    retain:
      hourly: 24
      daily: 7
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    accessModes:
      - ReadWriteOnce
