---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: app
spec:
  sourcePVC: app
  trigger:
    schedule: "0 2 * * *"
  restic:
    pruneIntervalDays: 7
    repository: app-volsync
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    copyMethod: Direct
