---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - externalsecret.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.2.4
    releaseName: grafana
    namespace: monitoring
    valuesFile: values.yaml
