annotations:
  reloader.stakater.com/auto: "true"
deploymentStrategy:
  type: Recreate
admin:
  existingSecret: grafana-admin-secret
env:
  GF_EXPLORE_ENABLED: true
  GF_SERVER_ROOT_URL: "https://grafana.pitower.link"
envFromSecret: grafana-secrets
grafana.ini:
  analytics:
    check_for_updates: false
    check_for_plugin_updates: false
    reporting_enabled: false
  auth:
    signout_redirect_url: "https://auth.pitower.link/logout"
    oauth_auto_login: true
    oauth_allow_insecure_email_lookup: true
  auth.generic_oauth:
    enabled: true
    name: Authelia
    icon: signin
    scopes: openid profile email groups
    client_id: grafana
    empty_scopes: false
    auth_url: https://auth.pitower.link/api/oidc/authorization
    token_url: https://auth.pitower.link/api/oidc/token
    api_url: https://auth.pitower.link/api/oidc/userinfo
    login_attribute_path: preferred_username
    groups_attribute_path: groups
    name_attribute_path: name
    use_pkce: true
  auth.generic_oauth.group_mapping:
    org_id: 1
    role_attribute_path: |
      contains(groups[*], 'admins') && 'Admin' || contains(groups[*], 'people') && 'Viewer'
  news:
    news_feed_enabled: false
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
      - name: flux
        orgId: 1
        folder: Flux
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/flux
      - name: kubernetes
        orgId: 1
        folder: Kubernetes
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/kubernetes
      - name: nginx
        orgId: 1
        folder: Nginx
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/nginx
      - name: github
        orgId: 1
        folder: GitHub
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/github
      - name: ceph
        orgId: 1
        folder: Ceph
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/ceph
datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - { name: Prometheus, orgId: 1 }
      - { name: Loki, orgId: 1 }
      - { name: Alertmanager, orgId: 1 }
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        jsonData:
          prometheusType: Prometheus
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-headless.monitoring.svc.cluster.local:3100
      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: http://alertmanager.monitoring.svc.cluster.local:9093
        jsonData:
          implementation: prometheus
      - name: GitHub
        type: grafana-github-datasource
        jsonData:
          owner: ""
          repository: ""
        secureJsonData:
          accessToken: "${SECRET_GRAFANA_GITHUB_TOKEN}"
dashboards:
  default:
    authelia:
      url: https://raw.githubusercontent.com/authelia/authelia/master/examples/grafana-dashboards/simple.json
      datasource: Prometheus
    cloudflared:
      gnetId: 17457 # https://grafana.com/grafana/dashboards/17457?tab=revisions
      revision: 6
      datasource:
        - { name: DS_PROMETHEUS, value: Prometheus }
    external-dns:
      gnetId: 15038 # https://grafana.com/grafana/dashboards/15038?tab=revisions
      revision: 3
      datasource: Prometheus
    external-secrets:
      url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
      datasource: Prometheus
    cert-manager:
      url: https://raw.githubusercontent.com/monitoring-mixins/website/master/assets/cert-manager/dashboards/cert-manager.json
      datasource: Prometheus
    node-exporter-full:
      gnetId: 1860 # https://grafana.com/grafana/dashboards/1860?tab=revisions
      revision: 37
      datasource: Prometheus
    cloudnativepg:
      url: https://raw.githubusercontent.com/cloudnative-pg/grafana-dashboards/main/charts/cluster/grafana-dashboard.json
      datasource: Prometheus
  flux:
    flux-cluster:
      url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/cluster.json
      datasource: Prometheus
    flux-control-plane:
      url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/control-plane.json
      datasource: Prometheus
    # flux-logs:
    #   url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/main/monitoring/configs/dashboards/logs.json
    #   datasource: Loki
  ceph:
    ceph-cluster:
      # renovate: dashboardName="Ceph Cluster"
      gnetId: 2842
      revision: 18
      datasource: Prometheus
    ceph-osd:
      # renovate: dashboardName="Ceph - OSD (Single)"
      gnetId: 5336
      revision: 9
      datasource: Prometheus
    ceph-pools:
      # renovate: dashboardName="Ceph - Pools"
      gnetId: 5342
      revision: 9
      datasource: Prometheus
  kubernetes:
    kubernetes-api-server:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
      datasource: Prometheus
    kubernetes-coredns:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
      datasource: Prometheus
    kubernetes-global:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
      datasource: Prometheus
    kubernetes-namespaces:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
      datasource: Prometheus
    kubernetes-nodes:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
      datasource: Prometheus
    kubernetes-pods:
      url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
      datasource: Prometheus
  nginx:
    nginx:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
      datasource: Prometheus
    nginx-request-handling-performance:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
      datasource: Prometheus
  github:
    github-repo-insights:
      gnetId: 14000 # https://grafana.com/grafana/dashboards/12239?tab=revisions
      revision: 1
      datasource: GitHub
sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
    labelValue: ""
    label: grafana_dashboard
    folderAnnotation: grafana_folder
    provider:
      disableDelete: true
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    searchNamespace: ALL
    labelValue: ""
serviceMonitor:
  enabled: true

route:
  main:
    enabled: true
    hostnames:
      - grafana.pitower.link
    parentRefs:
      - name: envoy-external
        namespace: networking
        sectionName: https

# ingress:
#   enabled: true
#   ingressClassName: external
#   annotations:
#     external-dns.alpha.kubernetes.io/target: external.pitower.link
#   hosts:
#     - &host "grafana.pitower.link"
#   tls:
#     - hosts:
#         - *host

persistence:
  enabled: false

testFramework:
  enabled: false

plugins:
  - grafana-worldmap-panel
  - grafana-clock-panel
  - grafana-github-datasource

servuceMonitor:
  enabled: true

imageRenderer:
  enabled: true
