---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 30Gi
              storageClass: ceph-block
              globalMounts:
                - path: /config

        pod:
          enableServiceLinks: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
            kubernetes.io/arch: amd64
            kubernetes.io/hostname: "worker-04"
          securityContext:
            privileged: true
          volumeMounts:
            - name: quicksync
              mountPath: /dev/dri
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 2024123005
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 500000000
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 1024M
              limits:
                gpu.intel.com/i915: 1
                memory: 8192M
        volumes:
          - name: quicksync
            hostPath:
              path: /dev/dri
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          external-dns.alpha.kubernetes.io/hostname: jellyfin.${SECRET_DOMAIN}
          io.cilium/lb-ipam-ips: "192.168.0.229"
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host jellyfin.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        type: nfs
        server: data
        path: /volume1/media
        globalMounts:
          - path: /data/nas-media
      transcode:
        type: emptyDir
      tmp:
        type: emptyDir
