---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../../../components/volsync
configMapGenerator:
  - name: volsync-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=radarr
      - CLAIM_NAME=radarr-config
      - SECRET_NAME=radarr-volsync
      - STORAGE_SIZE=2Gi
      - RESTIC_REPO=s3:https://s3.eu-central-2.amazonaws.com/pitower-volsync-backups/media/radarr
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 4.6.2
    releaseName: radarr
    namespace: media
    valuesFile: values.yaml
