controllers:
  radarr:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 6.4.0.10523@sha256:846f8574f2745d9f713981dd6dea3041cab27110b5517f30b533252283d6d25d
        env:
          RADARR__INSTANCE_NAME: Radarr
          RADARR__PORT: &port 7878
          RADARR__AUTHENTICATION_METHOD: External
          RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          RADARR__APPLICATION_URL: "https://radarr.wibrow.dev"
          RADARR__LOG_LEVEL: info
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 10m
            memory: 203Mi
          limits:
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
service:
  app:
    controller: radarr
    ports:
      http:
        port: *port

route:
  app:
    hostnames:
      - radarr.wibrow.dev
    parentRefs:
      - name: envoy-internal
        namespace: networking
        sectionName: https

persistence:
  config:
    enabled: true
    existingClaim: radarr-config
  add-ons:
    type: emptyDir
  tmp:
    type: emptyDir
  media:
    type: nfs
    server: data
    path: /volume1/media
    globalMounts:
      - path: /data/nas-media
