---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: headlamp-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: headlamp
        OIDC_CLIENT_SECRET: "{{ .client_secret }}"
        OIDC_ISSUER_URL: https://auth.wibrow.dev
        OIDC_SCOPES: openid profile email groups
        OIDC_USE_PKCE: "true"
  data:
    - secretKey: client_secret
      remoteRef:
        key: /system/headlamp/client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
