replicaCount: 1

serviceAccount:
  create: true

clusterRoleBinding:
  create: true
  clusterRoleName: cluster-admin

config:
  pluginsDir: /headlamp/plugins
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc
    usePKCE: true

persistentVolumeClaim:
  enabled: false

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: true
  hostnames:
    - headlamp.wibrow.dev
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 256Mi

pluginsManager:
  enabled: true
  version: latest
  configContent: |
    plugins:
      - name: cert-manager
        source: https://artifacthub.io/packages/headlamp/headlamp-cert-manager/cert-manager
        version: latest
      - name: ai-assistant
        source: https://artifacthub.io/packages/headlamp/headlamp-ai-assistant/ai-assistant
        version: latest
      - name: envoy-gateway
        source: https://artifacthub.io/packages/headlamp/headlamp-envoy-gateway/envoy-gateway
        version: latest
      - name: rook
        source: https://artifacthub.io/packages/headlamp/headlamp-rook/headlamp-rook-plugin
        version: latest
    installOptions:
      parallel: true
      maxConcurrent: 1
