---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname tandoor
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/pitower/apps/selfhosted/tandoor/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-stores
