---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./1password-connect/ks.yaml
  - ./external-secrets/ks.yaml
  - ./authelia/ks.yaml
  - ./lldap/ks.yaml
  - ./aws-identity-webhook/
