---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pitower
  namespace: actions
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller-charts/gha-runner-scale-set
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 30m
  values:
    runnerScaleSetName: default
    githubConfigUrl: https://github.com/swibrow/pitower
    githubConfigSecret: actions-runner-controller-auth
    minRunners: 0
    maxRunners: 10
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-block
        resources:
          requests:
            storage: 2Gi
      kubernetesModeServiceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::633355703129:role/pitower
    controllerServiceAccount:
      namespace: actions
      name: actions-runner-controller-gha-rs-controller
