controllers:
  prowlarr:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch

    containers:
      app:
        image:
          repository: ghcr.io/onedr0p/prowlarr-nightly
          tag: 1.33.0.4991@sha256:d28c4bf4276143c5b9a51452ef9710f7d65944b32432aeb5443a0e1641d7eb5f
        env:
          COMPlus_EnableDiagnostics: "0"
          PROWLARR__INSTANCE_NAME: Prowlarr
          PROWLARR__PORT: &port 9696
          PROWLARR__LOG_LEVEL: info
          PROWLARR__ANALYTICS_ENABLED: "False"
          PROWLARR__AUTHENTICATION_METHOD: External
          PROWLARR__API_KEY:
            valueFrom:
              secretKeyRef:
                name: prowlarr-secret
                key: api_key
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 18m
            memory: 128Mi
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    controller: prowlarr
    ports:
      http:
        port: *port

ingress:
  app:
    className: internal
    hosts:
      - host: prowlarr.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http

persistence:
  config:
    existingClaim: prowlarr-config
