---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-issuers
  path: ./kubernetes/pitower/apps/networking/nginx/certificates
  prune: false
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-external
  namespace: flux-system
spec:
  dependsOn:
    - name: nginx-certificates
  path: ./kubernetes/pitower/apps/networking/nginx/external
  prune: false
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-internal
  namespace: flux-system
spec:
  dependsOn:
    - name: nginx-certificates
  path: ./kubernetes/pitower/apps/networking/nginx/internal
  prune: false
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
