---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./stores

helmCharts:
  - name: external-secrets
    version: 0.17.0
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    namespace: security
    valuesInline:
      installCRDs: true
      replicaCount: 1
      leaderElect: true
      grafana:
        enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
      backgroundController:
        serviceMonitor:
          enabled: true
          interval: 1m
      cleanupController:
        serviceMonitor:
          enabled: true
          interval: 1m
      reportsController:
        serviceMonitor:
          enabled: true
          interval: 1m
