apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-automation
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  apps/home-automation: "true"
          - git:
              repoURL: https://github.com/swibrow/home-ops
              revision: main
              directories:
                - path: kubernetes/apps/home-automation/*
                - path: kubernetes/apps/home-automation/home-assistant
                  exclude: true
                - path: kubernetes/apps/home-automation/zigbee2mqtt
                  exclude: true
                - path: kubernetes/apps/home-automation/mosquitto
                  exclude: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "{{.name}}-{{index .path.segments 2}}-{{.path.basename}}"
      namespace: argocd
      labels:
        app.kubernetes.io/cluster: "{{.name}}"
        app.kubernetes.io/category: "{{index .path.segments 2}}"
        app.kubernetes.io/name: "{{index .path.segments 3}}"
        app.kubernetes.io/instance: "{{index .path.segments 3}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: apps
      source:
        repoURL: https://github.com/swibrow/home-ops
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
        namespace: "{{index .path.segments 2}}"
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 3
