---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  repo:
    desc: Open the repository in the browser
    cmds:
      - gh repo view --web

  update-environment-variables:
    desc: Update the environment variables in the repository
    cmds:
      - gh variable set -f .config/.env.{{.ENVIRONMENT}} --env {{.ENVIRONMENT}}
