controllers:
  house-hunter:
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      app:
        image:
          repository: ghcr.io/swibrow/house-hunter
          tag: latest
          pullPolicy: Always
        env:
          POSTGRES_HOST:
            valueFrom:
              secretKeyRef:
                name: house-hunter-db-secret
                key: DB_HOST
          POSTGRES_PORT:
            valueFrom:
              secretKeyRef:
                name: house-hunter-db-secret
                key: DB_PORT
          POSTGRES_USER:
            valueFrom:
              secretKeyRef:
                name: house-hunter-db-secret
                key: DB_USER
          POSTGRES_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: house-hunter-db-secret
                key: DB_PASS
          POSTGRES_DB:
            valueFrom:
              secretKeyRef:
                name: house-hunter-db-secret
                key: DB_NAME
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  app:
    controller: house-hunter
    ports:
      http:
        port: 8000

route:
  app:
    enabled: true
    hostnames:
      - house-hunter.pitower.link
      - house-hunter.wibrow.dev
    parentRefs:
      - name: envoy-external
        namespace: networking
        sectionName: https

# ingress:
#   app:
#     className: external
#     annotations:
#       external-dns.alpha.kubernetes.io/target: external.pitower.link
#     hosts:
#       - host: &host house-hunter.pitower.link
#         paths:
#           - path: /
#             service:
#               identifier: app
#               port: http
#     tls:
#       - hosts:
#           - *host
