---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homepage
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/pitower/apps/selfhosted/homepage/app
  postBuild:
    substitute:
      HOSTNAME: home.${SECRET_DOMAIN}
  prune: false
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: true
