controllers:
  mealie:
    containers:
      app:
        image:
          repository: ghcr.io/mealie-recipes/mealie
          tag: v3.16.0
        env:
          ALLOW_SIGNUP: "false"
          BASE_URL: https://recipes.wibrow.dev
          TZ: Europe/Zurich
          OIDC_AUTH_ENABLED: "true"
          OIDC_CONFIGURATION_URL: https://auth.pitower.link/.well-known/openid-configuration
          OIDC_CLIENT_ID: mealie
          OIDC_AUTO_REDIRECT: "true"
          OIDC_SIGNUP_ENABLED: "true"
          OIDC_ADMIN_GROUP: admins
          OIDC_USER_GROUP: apps
        envFrom:
          - secretRef:
              name: mealie-secret
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                port: &port 9000
                path: /api/app/about
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  app:
    controller: mealie
    ports:
      http:
        port: *port

route:
  app:
    enabled: true
    hostnames:
      - recipes.pitower.link
      - recipes.wibrow.dev
    parentRefs:
      - name: envoy-external
        namespace: networking
        sectionName: https

persistence:
  data:
    existingClaim: mealie-data
    globalMounts:
      - path: /app/data
