---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cryptgeon
  namespace: tools
spec:
  interval: 30m
  chart:
    spec:
      chart: cryptgeon
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: swibrow
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    redisEndpoint: redis://default:OoEJQOlAF3@cryptgeon-redis-master.tools.svc.cluster.local  # TODO: use secret
    redis:
      enabled: true
      auth.enabled: false
      architecture: standalone
      master:
        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 256Mi
      metrics.enabled: true
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
      hosts:
        - host: &host "secrets.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
