---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.29.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
      ingester:
        chunk_encoding: snappy
      limits_config:
        retention_period: 14d
      schemaConfig:
        configs:
        - from: "2024-04-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem
          schema: v13
      storage:
        type: filesystem

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 20Gi

    backend:
      replicas: 0
    chunksCache:
      enabled: false
    gateway:
      replicas: 0
    lokiCanary:
      enabled: false
    read:
      replicas: 0
    resultsCache:
      enabled: false
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
    test:
      enabled: false
    write:
      replicas: 0
