apiVersion: v1
kind: Service
metadata:
  name: garrison-keep
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garrison-keep
spec:
  selector:
    app.kubernetes.io/name: garrison-keep
  ports:
    - name: http
      port: {{ .Values.keep.port }}
      targetPort: http
