apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: actions-runner-controller
  namespace: actions
  labels:
    app.kubernetes.io/instance: actions-runner-controller
spec:
  jobLabel: actions-runner-controller
  namespaceSelector:
    matchNames:
    - actions
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: actions-runner-controller
