---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: browser-use
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: browser-use-secret
    creationPolicy: Owner
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: /ai/browser-use/anthropic-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
