---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      plex:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.41.6.9685
            env:
              PLEX_ADVERTISE_URL: https://192.168.0.228:32400,https://plex.pitower.link:443
              PLEX_NO_AUTH_NETWORKS: 192.168.0.0/24
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities:
            #     drop:
            #       - ALL
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
                gpu.intel.com/i915: 1
              limits:
                cpu: 4000m
                gpu.intel.com/i915: 1
                memory: 4096M

    service:
      app:
        controller: plex
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: plex.${SECRET_DOMAIN}
          lbipam.cilium.io/ips: "192.168.0.228"
        ports:
          http:
            port: &port 32400

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: plex-config
        advancedMounts:
          plex:
            app:
              - path: /config
      plex-cache:
        existingClaim: plex-cache
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
      media:
        type: nfs
        server: data
        path: /volume1/media
        advancedMounts:
          plex:
            app:
              - path: /data/nas-media
      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode
      # quicksync:
      #   type: hostPath
      #   hostPath: /dev/dri
      #   hostPathType: Directory
      #   advancedMounts:
      #     plex:
      #       app:
      #        - path: /dev/dri
