---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: plex
  app.kubernetes.io/instance: plex
