ndm:
  enabled: false
ndmOperator:
  enabled: false
localprovisioner:
  enabled: true
  image: quay.io/openebs/provisioner-localpv
  deviceClass:
    enabled: false
  hostpathClass:
    enabled: true
    name: openebs-hostpath
    isDefaultClass: false
    basePath: /var/openebs/local
