apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: Cloudsnacks Backstage
      # Should be the same as backend.baseUrl when using the `app-backend` plugin.
      baseUrl: ${HOST:-http://localhost:7007}

    organization:
      name: cloudsnacks

    backend:
      baseUrl: ${HOST:-http://localhost:7007}
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: ${HOST:-http://localhost:7007}
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      # config options: https://node-postgres.com/apis/client
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          # https://node-postgres.com/features/ssl
          # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
          # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
          # ssl:
          #   ca: # if you have a CA file and want to verify it you can uncomment this section
          #     $file: <file-path>/ca/server.crt
    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'docker' # Alternatives - 'local'
      publisher:
        type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            signIn:
              resolvers:
                - resolver: usernameMatchingUserEntityName
                - resolver: emailMatchingUserEntityProfileEmail
                - resolver: emailLocalPartMatchingUserEntityName

    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${AUTH_ORG_APP_ID}
              clientId: ${AUTH_ORG_CLIENT_ID}
              clientSecret: ${AUTH_ORG_CLIENT_SECRET}
              privateKey: ${AUTH_ORG_PRIVATE_KEY}
              webhookSecret: ${AUTH_ORG_WEBHOOK_SECRET}
              # The following line is optional and can be used to specify the installation id
              # installationId: 12345
              # The following line is optional and can be used to specify the webhook url
              webhookUrl: ${AUTH_ORG_WEBHOOK_URL}

    catalog:
      providers:
        githubOrg:
          id: github
          githubUrl: https://github.com
          orgs: ['cloudsnacks']
          schedule:
            initialDelay: { seconds: 30 }
            frequency: { hours: 1 }
            timeout: { minutes: 50 }

      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location]
      locations:
        # Local example data, file locations are relative to the backend process, typically `packages/backend`
        - type: file
          target: ../../examples/entities.yaml

        # Local example template
        - type: file
          target: ../../examples/template/template.yaml
          rules:
            - allow: [Template]

        # Local example organizational data
        - type: file
          target: ../../examples/org.yaml
          rules:
            - allow: [User, Group]

        # # Uncomment these lines to add more example data
        # - type: url
        #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

        # # Uncomment these lines to add an example org
        # - type: url
        #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
        #   rules:
        #     - allow: [User, Group]

    scaffolder:
      defaultAuthor:
        name: 'Cloud Snacks'
        email: git@cloudsnacks.ch
      defaultCommitMessage: "feat: its all downhill from here"
