---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
spec:
  interval: 30m
  chart:
    spec:
      chart: backstage
      version: 1.9.5
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: backstage
  values:
    backstage:
      image:
        repository: cloudsnacks/backstage
        tag: 0540057b1035839051b109bb973c33ddbcd17f32
      command:
        - node
        - packages/backend
      extraAppConfig:
        - filename: app-config.yaml
          configMapRef: backstage-app-config
      extraEnvVars:
        - name: NODE_ENV
          value: development
      extraEnvVarsSecrets:
        - backstage-secrets
        - backstage-db-secrets
    ingress:
      enabled: true
      className: external
      host: backstage.pitower.link
      path: "/"
      tls:
        enabled: true
