---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: paperless-ai-secrets
  data:
    - secretKey: PAPERLESS_API_TOKEN
      remoteRef:
        key: /banking/paperless-ai/PAPERLESS_API_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AI_PROVIDER
      remoteRef:
        key: /banking/paperless-ai/AI_PROVIDER
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CUSTOM_BASE_URL
      remoteRef:
        key: /banking/paperless-ai/CUSTOM_BASE_URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CUSTOM_API_KEY
      remoteRef:
        key: /banking/paperless-ai/CUSTOM_API_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: CUSTOM_MODEL
      remoteRef:
        key: /banking/paperless-ai/CUSTOM_MODEL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
