---
originRequest:
  http2Origin: true

ingress:
  - hostname: "pitower.link"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.pitower.link"
  - hostname: "*.pitower.link"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "external.pitower.link"
  - service: http_status:404
