---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - externalsecret.yaml
  - tcproute.yaml
components:
  - ../../../../components/cnpg-db
configMapGenerator:
  - name: cnpg-db-config
    literals:
      - APP_NAME=lldap
      - SECRET_NAME=lldap-db-secret
      - CNPG_SECRET_KEY=lldap-app
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 4.6.2
    releaseName: lldap
    namespace: security
    valuesFile: values.yaml
