---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-importer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: firefly-importer-secrets

  data:
    - secretKey: APP_KEY
      remoteRef:
        key: /banking/firefly-importer/APP_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AUTO_IMPORT_SECRET
      remoteRef:
        key: /banking/firefly-importer/AUTO_IMPORT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: FIREFLY_III_ACCESS_TOKEN
      remoteRef:
        key: /banking/firefly-importer/FIREFLY_III_ACCESS_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: IMPORT_DIR_ALLOWLIST
      remoteRef:
        key: /banking/firefly-importer/IMPORT_DIR_ALLOWLIST
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: MAIL_FROM
      remoteRef:
        key: /banking/firefly-importer/MAIL_FROM
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: NORDIGEN_ID
      remoteRef:
        key: /banking/firefly-importer/NORDIGEN_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: NORDIGEN_KEY
      remoteRef:
        key: /banking/firefly-importer/NORDIGEN_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: STATIC_CRON_TOKEN
      remoteRef:
        key: /banking/firefly-importer/STATIC_CRON_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None