---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.1
    releaseName: cert-manager
    includeCRDs: true
    namespace: cert-manager
    valuesFile: values.yaml
