---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    version: 1.43.2
    releaseName: coredns
    namespace: kube-system
    valuesFile: values.yaml
  - name: k8s-gateway
    repo: https://ori-edge.github.io/k8s_gateway/
    version: 2.4.0
    releaseName: k8s-gateway
    namespace: kube-system
    valuesInline:
      fullnameOverride: k8s-gateway
      domain: pitower.link
      ttl: 1
      service:
        type: LoadBalancer
        port: 53
        annotations:
          io.cilium/lb-ipam-ips: "192.168.0.220"
        externalTrafficPolicy: Cluster
