blueprint:
  name: Motion-activated Light/Switch
  source_url: https://github.com/swibrow/home-ops/blob/main/iot/homeassistant/blueprints/motion_activated_light.yaml
  description: |
    Run custom actions when motion is detected.
    Supports any action for both motion detected and motion cleared events.

    Actions are triggered when motion is detected and again after a
    configurable delay once motion stops.
  domain: automation
  author: Home Assistant
  input:
    motion_entity:
      name: Motion Sensor
      description: The motion or occupancy sensor to monitor
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    motion_detected_action:
      name: Motion Detected Action
      description: Action to run when motion is detected (e.g., turn on light, run scene)
      default: []
      selector:
        action: {}
    motion_cleared_action:
      name: Motion Cleared Action
      description: Action to run after motion stops and wait time elapses (e.g., turn off light)
      default: []
      selector:
        action: {}
    no_motion_wait:
      name: Wait time
      description: Time to wait after last motion before running motion cleared action
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

actions:
  - alias: "Run motion detected action"
    choose:
      - conditions: "{{ true }}"
        sequence: !input motion_detected_action
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      trigger: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Run motion cleared action"
    choose:
      - conditions: "{{ true }}"
        sequence: !input motion_cleared_action
