---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-pihole
  namespace: flux-system
spec:
  path: ./pitower/kubernetes/infra/networking/pihole/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: pihole
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: rook-ceph
