---
- name: Install corosync-qnetd
  ansible.builtin.apt:
    name: corosync-qnetd
    state: present
    update_cache: true

- name: Ensure corosync-qnetd is enabled and running
  ansible.builtin.systemd_service:
    name: corosync-qnetd
    enabled: true
    state: started

- name: Create root .ssh directory
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Authorize PVE cluster node root keys for qdevice setup
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys
    line: "{{ item }}"
    create: true
    owner: root
    group: root
    mode: "0600"
  loop: "{{ corosync_qnetd_cluster_node_keys }}"
  loop_control:
    label: "{{ item.split(' ')[-1] }}"
