controllers:
  echo-server:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: "true"
          LOG_IGNORE_PATH: /healthz
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            memory: 64Mi
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
service:
  app:
    ports:
      http:
        port: 8080
route:
  app:
    enabled: true
    hostnames:
      - echo.pitower.link
    parentRefs:
      - name: envoy-external
        namespace: networking
        sectionName: https
