---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/pitower/apps/media/plex/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
