fullnameOverride: victoria-logs

server:
  enabled: true
  fullnameOverride: victoria-logs
  replicaCount: 1
  retentionPeriod: 14d
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    size: 20Gi
  service:
    servicePort: 9428
    type: ClusterIP
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 1Gi

dashboards:
  enabled: true
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_folder: VictoriaLogs
