---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./reloader/ks.yaml
  - ./volsync/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./intel-device-plugins/ks.yaml
