#!/usr/bin/env python3
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

import requests
import yaml

REPO_HOST_PATH = "github.com/swibrow/home-ops.git"
MODELS_REL_PATH = "kubernetes/apps/pitower/ai/agentgateway/config/models-openrouter.yaml"
APPROVED_REL_PATH = "kubernetes/apps/pitower/workflows/agentgateway-model-sync/approved-models.yaml"
BRANCH = "automation/agentgateway-model-sync"
MIN_CREATED = datetime.fromisoformat(os.environ.get("MIN_CREATED", "2026-09-01")).replace(tzinfo=timezone.utc)

HEADER = """\
# Generated by the agentgateway-model-sync CronWorkflow
# (workflows/agentgateway-model-sync): one AgentgatewayModel per approved
# OpenRouter model, so it is listed on /v1/models under its OpenRouter id.
# Unlisted ids still route through the zz-openrouter catch-all in models.yaml.
"""

MODEL_TEMPLATE = """\
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayModel
metadata:
  name: {name}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: agentgateway
      sectionName: http
  match:
    model: {model_id}
  provider: Openrouter
  policies:
    auth:
      secretRef:
        name: agentgateway-providers
        key: OPENROUTER_API_KEY
"""


def run(*args, cwd=None):
    return subprocess.run(args, cwd=cwd, check=True, capture_output=True, text=True)


def git_clone(repo_dir, token):
    run("git", "clone", "--depth", "50", f"https://x-access-token:{token}@{REPO_HOST_PATH}", repo_dir)
    run("git", "config", "user.name", "agentgateway-model-sync", cwd=repo_dir)
    run("git", "config", "user.email", "actions@wibrow.dev", cwd=repo_dir)


def load_existing(models_path):
    if not os.path.exists(models_path):
        return set()
    with open(models_path) as f:
        return {d["spec"]["match"]["model"] for d in yaml.safe_load_all(f) if d}


def load_families(approved_path):
    with open(approved_path) as f:
        return {name: re.compile(pattern) for name, pattern in yaml.safe_load(f)["families"].items()}


def fetch_catalog():
    resp = requests.get("https://openrouter.ai/api/v1/models", timeout=30)
    resp.raise_for_status()
    return resp.json()["data"]


def find_candidates(catalog, existing_ids, families):
    candidates = []
    for m in catalog:
        model_id = m.get("id", "")
        if model_id in existing_ids or ":" in model_id or model_id.startswith("~"):
            continue
        if datetime.fromtimestamp(m.get("created", 0), timezone.utc) < MIN_CREATED:
            continue
        if any(p.search(model_id) for p in families.values()):
            candidates.append(m)
    return sorted(candidates, key=lambda m: m["id"])


def resource_name(model_id):
    return "openrouter-" + re.sub(r"[^a-z0-9.-]+", "-", model_id.lower()).strip("-.")


def render(model_ids):
    return HEADER + "".join(
        MODEL_TEMPLATE.format(name=resource_name(i), model_id=i) for i in sorted(model_ids)
    )


def pr_body(candidates):
    lines = [
        f"New OpenRouter models from the approved families in `{APPROVED_REL_PATH}`, "
        f"created on or after {MIN_CREATED:%Y-%m-%d}.",
        "",
        "| Model | Created | Context | Prompt $/M | Completion $/M |",
        "|---|---|---|---|---|",
    ]
    for m in candidates:
        pricing = m.get("pricing", {})
        prompt = float(pricing.get("prompt", 0) or 0) * 1_000_000
        completion = float(pricing.get("completion", 0) or 0) * 1_000_000
        created = datetime.fromtimestamp(m.get("created", 0), timezone.utc)
        lines.append(
            f"| `{m['id']}` | {created:%Y-%m-%d} | {m.get('context_length', '?')} | "
            f"${prompt:.2f} | ${completion:.2f} |"
        )
    return "\n".join(lines)


def open_or_update_pr(token, title, body):
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"}
    api = "https://api.github.com/repos/swibrow/home-ops"
    resp = requests.get(
        f"{api}/pulls", headers=headers, params={"head": f"swibrow:{BRANCH}", "state": "open"}, timeout=30
    )
    resp.raise_for_status()
    if open_prs := resp.json():
        number = open_prs[0]["number"]
        requests.patch(
            f"{api}/pulls/{number}", headers=headers, json={"title": title, "body": body}, timeout=30
        ).raise_for_status()
        print(f"updated PR #{number}")
    else:
        r = requests.post(
            f"{api}/pulls",
            headers=headers,
            json={"title": title, "body": body, "head": BRANCH, "base": "main"},
            timeout=30,
        )
        r.raise_for_status()
        print(f"opened PR #{r.json()['number']}")


def main():
    # --local rewrites the file in the current checkout without git or a PR.
    local = "--local" in sys.argv
    repo_dir = os.getcwd() if local else "/work/home-ops"
    if not local:
        git_clone(repo_dir, os.environ["GITHUB_TOKEN"])

    models_path = os.path.join(repo_dir, MODELS_REL_PATH)
    existing_ids = load_existing(models_path)
    candidates = find_candidates(fetch_catalog(), existing_ids, load_families(os.path.join(repo_dir, APPROVED_REL_PATH)))
    if not candidates:
        print("no new approved models")
        return

    print(f"found {len(candidates)} new model(s):")
    for m in candidates:
        print(f"  {m['id']}")

    with open(models_path, "w") as f:
        f.write(render(existing_ids | {m["id"] for m in candidates}))
    if local:
        return

    run("git", "checkout", "-B", BRANCH, cwd=repo_dir)
    run("git", "add", MODELS_REL_PATH, cwd=repo_dir)
    title = f"feat(agentgateway): add {len(candidates)} new OpenRouter model(s)"
    run("git", "commit", "-m", title, cwd=repo_dir)
    run("git", "push", "-f", "origin", BRANCH, cwd=repo_dir)
    open_or_update_pr(os.environ["GITHUB_TOKEN"], title, pr_body(candidates))


if __name__ == "__main__":
    main()
