---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-chartselm
    version: 9.2.1
    releaseName: grafana
    valuesFile: values.yaml
