---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-external-dns
  path: ./pitower/kubernetes/infra/networking/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
