---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto
      namespace: home-automation
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            sonoff.feature.node.kubernetes.io/zigbee: "true"
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.1.3
            env:
              TZ: Europe/Zurich
              ZIGBEE2MQTT_DATA: /data
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_EXPERIMENTAL_EVENT_ENTITIES: true
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: true # Revert when blueprints are updated to support z2m 2.0
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: true # Revert when blueprints are updated to support z2m 2.0
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: true # Revert when blueprints are updated to support z2m 2.0
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: true # Revert when blueprints are updated to support z2m 2.0
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: true # Revert when blueprints are updated to support z2m 2.0
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: true
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "https://zigbee.${SECRET_DOMAIN}"
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: true
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: false
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.home-automation.svc.cluster.local
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: true
              ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
              ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: false
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyACM0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ezsp
            securityContext:
              privileged: true
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.96.2@sha256:6b8c0e944caec80057e71d2c2f352cee38fe00ae4b7515fc4458eb300844f699
            args:
              - --auth
              - none
              - --disable-telemetry
              - --disable-update-check
              - --user-data-dir
              - /data/.code-server
              - --extensions-dir
              - /data/.code-server
              - --port
              - "12321"
              - /data
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            primary: true
            port: 8080
          metrics:
            port: 9000
          code-server:
            port: 12321

    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$1
        hosts:
          - host: &host "zigbee.${SECRET_DOMAIN}"
            paths:
              - path: /(.*)
                service:
                  identifier: app
                  port: http
              - path: /code/(.*)
                service:
                  identifier: app
                  port: code-server
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: zigbee2mqtt
        advancedMounts:
          zigbee2mqtt:
            app:
              - path: /data
            code-server:
              - path: /data
      usb:
        type: hostPath
        hostPath: /dev/ttyACM0
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/ttyACM0
