controllers:
  sonarr:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      nodeSelector:
        wibrow.dev/compute: "true"
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/sonarr
          tag: 4.0.19.3001@sha256:2fef93accb445aeb1773e454825ac903f7d66d9addfe045d56fff69ba8181c82
        env:
          SONARR__INSTANCE_NAME: Sonarr
          SONARR__PORT: &port 8989
          SONARR__AUTHENTICATION_METHOD: External
          SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
          SONARR__APPLICATION_URL: "https://sonarr.wibrow.dev"
          # SONARR__LOG_LEVEL: info
          # SONARR__API_KEY:
          #   valueFrom:
          #     secretKeyRef:
          #       name: sonarr-secret
          #       key: api_key
        resources:
          requests:
            cpu: 10m
            memory: 241Mi
          limits:
            memory: 768M

service:
  app:
    controller: sonarr
    ports:
      http:
        port: *port

route:
  app:
    hostnames:
      - sonarr.wibrow.dev
    parentRefs:
      - name: envoy-internal
        namespace: networking
        sectionName: https

persistence:
  config:
    enabled: true
    existingClaim: sonarr-config
  media:
    type: nfs
    server: data
    path: /volume1/media
    globalMounts:
      - path: /data/nas-media
