apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garrison
helmCharts:
  - name: garrison
    repo: oci://ghcr.io/swibrow/charts
    version: 0.11.0
    releaseName: garrison
    valuesFile: values.yaml
