---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - externalsecret.yaml
components:
  - ../../../../components/volsync
configMapGenerator:
  - name: volsync-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=prowlarr
      - CLAIM_NAME=prowlarr-config
      - SECRET_NAME=prowlarr-volsync
      - STORAGE_SIZE=1Gi
      - RESTIC_REPO=s3:https://s3.eu-central-2.amazonaws.com/pitower-volsync-backups/media/prowlarr
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 5.0.0
    releaseName: prowlarr
    namespace: media
    valuesFile: values.yaml
