apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WN1VlW022BVLIWolO3Bl65J3FunWCklvHDk9T2HxHG/xZ6yt,iv:avo69Hl238ZQe3lTiNCSbjMP7UihKlS3O503JCstqxg=,tag:K6uTXvvttlerG67mdug3/w==,type:str]
    credentials.json: ENC[AES256_GCM,data:oW4t0VFBbJIr5Jr6BMBlX7O6L0Wt+OmXEG0/KPZd70nmz48z/cOQb+zzC5WsIV/J4/SWbGTG1pnaKa+c+WKhv6XXEO4PNPXL61Vrsr6MvT6uZ9Zj/NdOyvipazJOF5obCVDYQEEt68L7iB2c7lRTxZ+KpbNxwGk/rTLU/eBnCLXHo7sxEdSLsuyuXSOVfUbVA37SGTBMwN4IYDVUu8g/0C7GSXbx3+3VBAKTy+0m,iv:f5j5DGaPRnYFE6zZXRQrPpBq6TXGqR7YEbXqWeVz0EU=,tag:NP/chirXz/Qt6iLmgUfgJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aG5PL3NxalpCVTdIczRU
            UWdwV0k2UjltTlNWdDZ6azFTaFlmWTB4UkZzCll0RkJHenJrM0ZidFRjMjd1amMv
            enFmbCtPdVBKSDYrOVVZelNCc3FIS2cKLS0tIGNRZGlVVEtCbmpHWmhYR0VJSDds
            TlFHMXNxSUxBMmFzUHJuSVdMUHluY0UK77S/5tms2UFh2AY2hQP+x/o/aFqswQk7
            Vb/+0fVCHcp5V4/FVO9S3FuLaQgUKyHRZNDHKKG9j+ak3WQhEguB5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-01T21:06:59Z"
    mac: ENC[AES256_GCM,data:EZBxPwWZ2aVAxhma7BkKYj/2lgbo8Q4/IISsniL1keoO7LC2m9UETzuwW2HKjKiyqbbS2cPkZ9y6Xrx22p6HD0abn+ai1mYOXFApXf50SMLFYnJhIdLfJIHxcf0Fn8JVHlVtbRooxx4qfJtVBTByffiHm7jclRvHnG1Nhe8P0r4=,iv:Js+37y5IBZrGapRCFB+2vVfSh7dBj2CWcqYSvCW7CAk=,tag:TFn+IvdYQztGLdCg+wHfzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
