githubConfigUrl: https://github.com/swibrow/how
githubConfigSecret: arc-github-app
runnerScaleSetName: how

controllerServiceAccount:
  name: arc-gha-rs-controller
  namespace: arc

minRunners: 0
maxRunners: 2

containerMode:
  type: dind

template:
  spec:
    serviceAccountName: how-runners
    automountServiceAccountToken: true
    nodeSelector:
      wibrow.dev/compute: "true"
    tolerations:
      - key: dedicated
        operator: Equal
        value: storage
        effect: NoSchedule
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:2.336.0
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 4Gi
