version: '3'

tasks:
  bootstrap:
    cmds:
      - sops --decrypt ./bootstrap/age-key.sops.yaml | kubectl apply -f -
      - sops --decrypt ./flux/vars/cluster-secrets.sops.yaml | kubectl apply -f -
      - kubectl apply --server-side --kustomize ./flux/config
      - kubectl apply --server-side --kustomize ./flux/repositories
      - kubectl apply --server-side --kustomize ./flux/vars
