---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workflows
resources:
  - externalsecret.yaml
  - rbac-sso.yaml
helmCharts:
  - name: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    version: 1.0.21
    releaseName: argo-workflows
    namespace: workflows
    valuesFile: values.yaml
    includeCRDs: true
