---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: ntfy-alertmanager-secret
    template:
      data:
        config: |
          http-address :8080
          log-level info
          alert-mode single

          labels {
              order "severity"
              severity "critical" {
                  priority 5
                  tags "rotating_light"
              }
              severity "warning" {
                  priority 4
                  tags "warning"
              }
              severity "info" {
                  priority 2
                  tags "information_source"
              }
          }

          resolved {
              update-notification true
              tags "white_check_mark"
              priority 2
          }

          ntfy {
              server http://ntfy.monitoring.svc.cluster.local
              topic pitower-alerts
              user bridge
              password "{{ .BRIDGE_PASSWORD }}"
              markdown true
          }
  data:
    - secretKey: BRIDGE_PASSWORD
      remoteRef:
        key: /monitoring/ntfy/BRIDGE_PASSWORD
