controllers:
  jellyfin:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      enableServiceLinks: false
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: "worker-04"
    containers:
      app:
        image:
          repository: jellyfin/jellyfin
          tag: "10.10.7"
        env:
          DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
        resources:
          requests:
            cpu: 100m
            gpu.intel.com/i915: 1
            memory: 1024M
          limits:
            gpu.intel.com/i915: 1
            memory: 8192M
service:
  app:
    controller: jellyfin
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: jellyfin.pitower.link
      io.cilium/lb-ipam-ips: "192.168.0.229"
    ports:
      http:
        port: 8096

ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.pitower.link
    hosts:
      - host: &host jellyfin.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host

persistence:
  config:
    existingClaim: config-jellyfin-0
    advancedMounts:
      jellyfin:
        app:
          - path: /config
  media:
    type: nfs
    server: data
    path: /volume1/media
    advancedMounts:
      jellyfin:
        app:
          - path: /data/nas-media
  tmpfs:
    type: emptyDir
    advancedMounts:
      jellyfin:
        app:
          - path: /cache
            subPath: cache
          - path: /transcode
            subPath: transcode
  quicksync:
    type: hostPath
    hostPath: /dev/dri
    hostPathType: Directory
    advancedMounts:
      jellyfin:
        app:
          - path: /dev/dri
