controllers:
  glance:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      glance:
        image:
          repository: docker.io/glanceapp/glance
          tag: v0.8.3@sha256:1fa252b1651c061cbe7a023326b314248bb820f81ee89a89970347b83684414c
        args:
          - --config
          - /config/glance.yml
        env:
          TZ: "${TIMEZONE}"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1022
    runAsGroup: 1022
    fsGroup: 1022
    fsGroupChangePolicy: OnRootMismatch
service:
  app:
    controller: glance
    ports:
      http:
        port: 8080
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.pitower.link
    hosts:
      - host: &host glance.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host
persistence:
  config:
    type: configMap
    name: glance-config
