otel_agent_otlp_api_key: ENC[AES256_GCM,data:f6j8YTBbA41ncFVFgrlvBeRh7ZV47IpSmRIYikZrpDtbu6UytEPah2U8h1+yov8MsB+s/Rj7aRS4esW+MC4Efw==,iv:tSGYPw/CsMunJCTw8H+o6HKLtxKpj67K8O5i8NvfL+4=,tag:UBWNa3DiIxX7pXSIZsPz3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR3RSaHBCaDB4S2YvLzRE
            Y0xKU1dicE1kS01rbk44Y0U3VDBiU2QwV1RVCjh5UE96bktvWVNXczNNNEtDOWh2
            ekFEakFGZjNCd3BSZDZLb2VkSlB4VHMKLS0tIDRjTnF0R2trVitOd0dURjNLTWQx
            MlpFT1pPUHNKUUFmQnJDNkZJR043YU0KQZsFbMw1TAlNoZzNZhm9mFxDuRLVFYAM
            /ViZ6UR+bC7ZJJalammqUPP3/wGh9tjXVPZXEx40g8hVihBbMxtCQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
    lastmodified: "2026-07-20T23:22:59Z"
    mac: ENC[AES256_GCM,data:u0B0jDL9/wMmwviGy+49qlmCli9FusTTpFu4/pxg8z749uQvTNv/RrWd/ITuwkzfSw0oPlL3AHRyKIxOAQtheAJY3rW9UAi1EXv7g2jTqysvvYyerz/q1r8N7d79Si4pyIPoyxwBwYxUxjYaSJxKljqYL76m5KLYWMZfwl53koY=,iv:msci87Pj6Nq4Hre7XYG6efpTizOt7cu50juXekSvIvA=,tag:NMvis5tHZ0zYO7TZcEBOBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
