---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 2.5.2
    releaseName: backstage
    valuesInline:
      backstage:
        image:
          repository: cloudsnacks/backstage
          tag: e8ecd4d142900aea82aae21975ff9e04813954c5
        command:
          - node
          - packages/backend
        extraAppConfig:
          - filename: app-config.yaml
            configMapRef: backstage-app-config
        extraEnvVars:
          - name: NODE_ENV
            value: development
        extraEnvVarsSecrets:
          - backstage-secrets
          - backstage-db-secrets
      ingress:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.pitower.link
        host: backstage.pitower.link
        path: /
        tls:
          enabled: true

# Additional Kubernetes resources
resources:
  - ./namespace.yaml
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./rbac.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: backstage
  app.kubernetes.io/instance: backstage
# Dependencies from Flux: cloudnative-pg-cluster
# Note: These need to be handled at the Flux Kustomization level
