controllers:
  excalidraw:
    replicas: 1
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: docker.io/excalidraw/excalidraw
          tag: latest@sha256:525d72908ffed09807bad50321b94698d725ddc5945118dc3e0b4a494f9772a8
          pullPolicy: IfNotPresent
        # probes:
        #   liveness:
        #     enabled: true
        #   readiness:
        #     enabled: true
        # resources:
        #   requests:
        #     cpu: 5m
        #     memory: 10Mi
        # limits:
        #   memory: 512Mi
        env:
          PORT: &port 8080
service:
  app:
    controller: excalidraw
    ports:
      http:
        port: *port
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.pitower.link
    hosts:
      - host: &host draw.pitower.link
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host
persistence:
  data:
    enabled: true
    type: emptyDir
