---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cnpg-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: cloudnative-pg
      server:
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          namespace: cloudnative-pg
          key: "ca.crt"
      auth:
        serviceAccount:
          name: external-secrets-pg
          namespace: cloudnative-pg
