controllers:
  autobrr:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        runAsNonRoot: true

    containers:
      app:
        image:
          repository: ghcr.io/autobrr/autobrr
          tag: v1.75.0
        env:
          AUTOBRR__CHECK_FOR_UPDATES: "false"
          AUTOBRR__HOST: 0.0.0.0
          AUTOBRR__PORT: &port 7474
          AUTOBRR__LOG_LEVEL: DEBUG
          AUTOBRR__DATABASE_TYPE: postgres
          AUTOBRR__POSTGRES_HOST:
            valueFrom:
              secretKeyRef:
                name: autobrr-db-secret
                key: DB_HOST
          AUTOBRR__POSTGRES_PORT:
            valueFrom:
              secretKeyRef:
                name: autobrr-db-secret
                key: DB_PORT
          AUTOBRR__POSTGRES_USER:
            valueFrom:
              secretKeyRef:
                name: autobrr-db-secret
                key: DB_USER
          AUTOBRR__POSTGRES_PASS:
            valueFrom:
              secretKeyRef:
                name: autobrr-db-secret
                key: DB_PASS
          AUTOBRR__POSTGRES_DATABASE:
            valueFrom:
              secretKeyRef:
                name: autobrr-db-secret
                key: DB_NAME
        envFrom:
          - secretRef:
              name: autobrr-secret
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  app:
    controller: autobrr
    ports:
      http:
        port: *port

route:
  app:
    hostnames:
      - autobrr.pitower.link
    parentRefs:
      - name: envoy-internal
        namespace: networking
        sectionName: https
