---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-metrics-server
  namespace: flux-system
spec:
  path: ./pitower/kubernetes/infra/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
