---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: security
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        LLDAP_JWT_SECRET: "{{ .lldap_jwt_secret }}"
        LLDAP_USER_PASS: "{{ .lldap_password }}"
        LLDAP_USER_DN: "{{ .lldap_user_dn }}"
        LLDAP_SERVER_KEY_SEED: "{{ .lldap_server_key_seed }}"
  dataFrom:
    - extract:
        key: lldap
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lldap_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cnpg-secrets
    kind: ClusterSecretStore
  target:
    name: lldap-db
    template:
      type: Opaque
      data:
        LLDAP_DATABASE_URL: '{{ index . "uri" }}'
        LLADP_DATABASE_NAME: '{{ index . "dbname" }}'
        POSTGRES_DBNAME: '{{ index . "dbname" }}'
        POSTGRES_HOST: '{{ index . "host" }}.database.svc.cluster.local'
        POSTGRES_PORT: '{{ index . "port" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASS: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: lldap-superuser
