---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      lldap:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          # secret.reloader.stakater.com/reload: lldap-secret, lldap-db-secret

        pod:
          # securityContext:
          #   runAsUser: 1000
          #   runAsGroup: 1000
          #   runAsNonRoot: true
          #   fsGroup: 1000
          #   fsGroupChangePolicy: "OnRootMismatch"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: lldap

        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.5.0
            command:
              - /app/lldap
            args:
              - run
            env:
              LLDAP_HTTP_PORT: &port 80
              LLDAP_HTTP_URL: https://lldap.pitower.link
              LLDAP_LDAP_PORT: &ldapPort 389
              LLDAP_LDAP_BASE_DN: dc=pitower,dc=link
            # envFrom:
              # - secretRef:
              #     name: lldap-secret
              # - secretRef:
              #     name: lldap-db-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi

    service:
      app:
        controller: lldap
        ports:
          http:
            port: *port
          ldap:
            port: *ldapPort

    ingress:
      app:
        className: "internal"
        hosts:
          - host: &hostName lldap.pitower.link
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName

    persistence:
      data:
        enabled: true
        existingClaim: lldap-data
