---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cnpg-secrets
    kind: ClusterSecretStore
  target:
    name: backstage-db-secrets
    template:
      type: Opaque
      data:
        POSTGRES_HOST: '{{ index . "host" }}.database.svc.cluster.local'
        POSTGRES_PORT: '{{ index . "port" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: backstage-superuser
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical

  target:
    name: auth-api

  # dataFrom will fetch all secrets that are inside the `secretsPath`. When `recursive` is
  # enabled, it will also fetch all secrets recursively in sub-directories.
  dataFrom:
    - find:
        name:
          regexp: .*
