---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-cert-manager
  namespace: flux-system
spec:
  path: ./pitower/kubernetes/infra/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-cert-manager
  path: ./pitower/kubernetes/infra/cert-manager/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
