nut_monitor_password: ENC[AES256_GCM,data:b2dfcsUHylzU3daXNBHTLcgHiAm2s8RH,iv:MAUPb0Ao9kZ4wJX5x1wQeGmFCPV5zbp7ZAFv4fXVqI8=,tag:6BAsD+07XGTEAS3C1hpq+g==,type:str]
nut_admin_password: ENC[AES256_GCM,data:YLOL+/OTpHHIPIcqNPFs4W5rauq/D1Uc,iv:OFda7UWDDlp4T5GlnUHphY21dfrcLtJK1zpkDz2fY4U=,tag:tgUIKbcNRBgxGbznwRrYQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRUlYS2JIZHlKOXJiWVVX
            K0hCQ0MwVG9sa3RDOFhiZ0prZ0U0Ri9OQVdnCkh0MVhHTHZ0TDhmeUhDYmtHbG0r
            cTFSUTR5YytndllqaVN6TS9UR1Bad0UKLS0tIHl4bVAzSm1DbDc2Q2ZIYUJlcHJK
            bG9jbzZpSmtEQVI3UjNZeWNXQStPcWsKOClAZGvL616/yd3EblfM0lG1uJufKchS
            k186IgNOLMHNsCkveB/kJEukq8pcCiGIS7/ttmN6BvEYYxOlCtw4QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
    lastmodified: "2026-06-19T09:29:57Z"
    mac: ENC[AES256_GCM,data:jQxSLpCimx07WhqSssubGwRKeJNAAL5IKZ8SPTMckLYJ8pWXYgpbFyWIR+q2a0Lc1h35yK/0dGKy4UlW6XUV4sZYqKB8rLs4Dl2eNZTgPCSYS/hTf5N/dSBTE+e4gi8Xo7XgPHH0cPBA3Xpn/G5H/x2oPj5AIm0eStcSMwHI+hE=,iv:hZzeJjmX3Mq/7ay82WL9R5Ggu7qUUPxU6GxxCUEzj6o=,tag:6RTt0iaeeHuLfAR1hQ4jEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
