---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-secret
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: readarr
        metadataPolicy: None
        property: api_key
      secretKey: api_key
