---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname readarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./pitower/kubernetes/apps/downloads/readarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: true
  dependsOn:
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "2000"
      APP_GID: "2000"
      VOLSYNC_CLAIM: readarr-config
