controllers:
  firefly:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: fireflyiii/core
          tag: version-6.5.1
        resources:
          requests:
            cpu: 15m
            memory: 128Mi
        envFrom:
          - secretRef:
              name: firefly-secrets
        env:
          TZ: Europe/Zurich
          DB_CONNECTION: pgsql
          DB_HOST:
            valueFrom:
              secretKeyRef:
                name: firefly-db-secrets
                key: DB_HOST
          DB_PORT:
            valueFrom:
              secretKeyRef:
                name: firefly-db-secrets
                key: DB_PORT
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: firefly-db-secrets
                key: DB_USER
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: firefly-db-secrets
                key: DB_PASS
          DB_DATABASE:
            valueFrom:
              secretKeyRef:
                name: firefly-db-secrets
                key: DB_NAME
          TRUSTED_PROXIES: "**"
          MAIL_MAILER: log
          MAIL_HOST: smtp-relay.gmail.com
          MAIL_PORT: 587
          ALLOW_WEBHOOKS: "true"
      cronjob:
        image:
          repository: alpine
          tag: 3.23.4
          pullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - >-
            echo "0 17 * * * wget -qO- http://firefly:8080/api/v1/cron/$(STATIC_CRON_TOKEN)"
            | crontab -
            && crond -f -L /dev/stdout
service:
  app:
    controller: firefly
    ports:
      http:
        port: 8080
route:
  app:
    hostnames:
      - money.pitower.link
    parentRefs:
      - name: envoy-internal
        namespace: networking
        sectionName: https
persistence:
  data:
    existingClaim: firefly-data
    advancedMounts:
      firefly:
        app:
          - path: /var/www/html/storage/upload
