---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zigbee-device
spec:
  rules:
    - # Sonoff Zigbee 3.0 USB
      name: sonoff-zigbee
      labels:
        sonoff.feature.node.kubernetes.io/zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["02"] }
            vendor: { op: In, value: ["1a86"] }
            device: { op: In, value: ["55d4"] }
