towonel_hub_node_key: ENC[AES256_GCM,data:40BOxtS78IQ4h5VNyTQCS653lA1H4YJuSwdjPQXK3kFO7fcDXV4T9hhfe78=,iv:HLFiN8V7Mij3uNDvyhqG4vJ7dG25KzeZuUxYRwyShps=,tag:dzXpAEtbWymoTPZaW01rfw==,type:str]
towonel_hub_kek_key: ENC[AES256_GCM,data:2XLkR+XTEO7z/PhGLUcdBiOiNEGvcgLP8QpNafMddMst40Ot9JB3F8BCJPyM5Q4gEiDpqt2emM5JgDmT/ut6hRKjK7vJ9YsV1v2B89dHxGwWQF95IdgZ1Q==,iv:7rKoOi7RKqlEhmimi58uhQxRfBDxJ7PrpjzX2UlaxH8=,tag:hEmTBXJISyJv6MiFq/JBVQ==,type:str]
towonel_hub_invite_hash_key: ENC[AES256_GCM,data:iEnau4GamyQ6sifDLuTECSaKV4sv6w128baBS+antqPU+Y/P+XpFGBHlxSLvetVoJsEhmtJ2DJufAGV9CmvhIwWiBKVPKdV8Vs9ODqO9hDKonJKGDFI/Zg==,iv:67bjZjDAwo//YtQVieCudPi/G+PsPqULC/CIRMnfCJo=,tag:We11B4x2dC0axWXMzMLiDA==,type:str]
towonel_hub_operator_key: ENC[AES256_GCM,data:icdjsdvXPABj6dTD3jb7OlOW8+slBjKXCuALv4sNKv+GuDMUcFfOtKpnCTpEsrKQeQyM0LtS94Ic6n4Q,iv:0KNEMtOiEmgfDPM+JpiaVfHeqvyasx8rdaNx1wZY0UM=,tag:XNVkhN2Xu3yZjs+trl9xjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOamUzbjEyN05BVkJyNlNJ
            MEdlZklVeUt0QW9oNzVYbUw1M0Q3U21McEdvCndtZGJtdmNIQjdVRW9WOVhJWmJ4
            N0Rxd2twUDU0Q0M5dVNUbG40WnRUbXMKLS0tIGRBZkN3YU9idVBnQi9kQjlDc2M1
            VnpNNWFIbUNGSmh3bStUcUc2Y2VSQlUKYC0Pr3PaqLI3N9bsyMDCb0iQn22+GMPO
            5b/uFVdLlqrV7JFdiDCmA39PP2dcT9RNH7hWKisrOsvYi3DuFymXeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
    lastmodified: "2026-07-20T11:23:17Z"
    mac: ENC[AES256_GCM,data:06Ht+XMET8F2EGSF9eNiNSIC5mseAIcBmT8ubiAynhFyhvfcLfJKPpihifUWqDdwXC0yxSiNHsCP66k4vsB5wJrfI0h/3Pl8JqFlxtqep5f07phhQfYRzL6hQTQwqYz9RV+P+JkVLJ8m9HwWIr7JmYTFK0N/l8+gu8GGvv6Cj6s=,iv:BQGTaVheuBUFDbhKkM7BSYu0VTjIraNWiRFtWBWzMhY=,tag:BGRqqlVAxOZHShXsE4vOfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
