controllers:
  whoami:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: docker.io/traefik/whoami
          tag: v1.11.0
        env:
          WHOAMI_PORT_NUMBER: &port 8080
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                port: *port
          readiness: *probes
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
service:
  app:
    controller: whoami
    ports:
      http:
        port: *port

route:
  app:
    enabled: true
    hostnames:
      - whoami.wibrow.dev
    parentRefs:
      - name: envoy-external
        namespace: networking
        sectionName: https
