---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tandoor-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .tandoor_secret_key }}"
        # LDAP
        LDAP_AUTH: "1"
        AUTH_LDAP_ALWAYS_UPDATE_USER: "1"
        AUTH_LDAP_BIND_DN: "{{ .lldap_user_dn }}"
        AUTH_LDAP_BIND_PASSWORD: "{{ .lldap_password }}"
        AUTH_LDAP_SERVER_URI: ldap://lldap.security.svc.cluster.local:5389
        AUTH_LDAP_USER_SEARCH_BASE_DN: "ou=people,dc=pitower,dc=link"
        AUTH_LDAP_USER_SEARCH_FILTER_STR: "(&(&(objectclass=person)(memberOf=cn=auth_users,ou=groups,dc=pitower,dc=link))(uid=%(user)s))"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: lldap
        metadataPolicy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lldap_$1"
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: tandoor
        metadataPolicy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "tandoor_$1"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cnpg-secrets
    kind: ClusterSecretStore
  target:
    name: tandoor-db-secret
    template:
      type: Opaque
      data:
        DB_ENGINE: django.db.backends.postgresql
        POSTGRES_HOST: '{{ index . "host" }}.database.svc.cluster.local'
        POSTGRES_PORT: '{{ index . "port" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_DB: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: tandoor-app
        metadataPolicy: None
