---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: github
  namespace: renovate
spec:
  # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
  image: ghcr.io/renovatebot/renovate:43.244.4
  schedule: "0 2,6 * * *"
  parallelism: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
  provider:
    name: github
  githubAppReference:
    secretName: renovate-secret
    appIdSecretKey: app_id
    installationIdSecretKey: installation_id
    pemSecretKey: private_key
  discoveryFilters:
    - swibrow/*
  skipForks: true
  extraEnv:
    - name: RENOVATE_INHERIT_CONFIG
      value: "true"
    - name: RENOVATE_ONBOARDING
      value: "false"
    - name: RENOVATE_REQUIRE_CONFIG
      value: "optional"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 4096Mi
