---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app excalidraw
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      excalidraw:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/excalidraw/excalidraw
              tag: latest@sha256:f771e6ec4cf117163c9a0adf7219dd523764f7463012c8eb4238d13c408e16f2
              pullPolicy: IfNotPresent
            # probes:
            #   liveness:
            #     enabled: true
            #   readiness:
            #     enabled: true
            # resources:
            #   requests:
            #     cpu: 5m
            #     memory: 10Mi
              # limits:
              #   memory: 512Mi
            env:
              PORT: &port 8080
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host draw.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: emptyDir
