---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - pki.yaml

helmCharts:
  - name: snapshot-controller
    repo: https://piraeus.io/helm-charts/
    version: 4.0.2
    releaseName: snapshot-controller
    includeCRDs: true
    namespace: system
    valuesFile: values.yaml
