---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-dp-gpu-device
spec:
  rules:
    - labels:
        intel.feature.node.kubernetes.io/quicksync: "true"
        intel.feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            device: { op: In, value: ["46D1"]}
            vendor: { op: In, value: ["8086"]}
      name: intel.gpu
