---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookbounty
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      bookbounty:
        annotations:
          reloader.stakater.com/auto: "true"
        # pod:
        #   securityContext:
        #     runAsUser: 1000
        #     runAsGroup: 1000
        #     runAsNonRoot: true
        #     fsGroup: 1000
        #     fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: thewicklowwolf/bookbounty
              tag: "0.2.2"
            env:
              readarr_address: "http://readarr.downloads.svc.cluster.local:8787"
              readarr_api_key:
                valueFrom:
                  secretKeyRef:
                    name: readarr-secret
                    key: api_key
              search_type: non-fiction
              libgen_address: http://libgen.is
            # probes:
            #   liveness:
            #     enabled: true
            #   readiness:
            #     enabled: true
            #   startup:
            #     enabled: true
            #     spec:
            #       failureThreshold: 30
            #       periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 224M
              # limits:
              #   memory: 224M
    service:
      app:
        controller: bookbounty
        ports:
          http:
            port: 5000

    ingress:
      app:
        className: internal
        hosts:
          - host: bookbounty.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: bookbounty-config
      downloads:
        type: nfs
        server: data
        path: /volume1/media/
        globalMounts:
          - path: /bookbounty/downloads
            subPath: downloads/bookbounty
