---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookbounty-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
