---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webhooks
  namespace: flux-system
spec:
  path: ./kubernetes/pitower/apps/flux-system/addons/webhooks
  prune: false
  sourceRef:
    kind: GitRepository
    name: pitower
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
