reloader:
  podMonitor:
    enabled: true

  reloadStrategy: annotations

  deployment:
    # krr: reloader-reloader/reloader-reloader
    resources:
      requests:
        cpu: 5m
        memory: 144Mi
      limits:
        memory: 256Mi
