---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &appname house-hunter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      house-hunter:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/swibrow/house-hunter
              tag: latest
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: house-hunter-db-secret
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /accounts/login/
            #         port: *tandoorPort
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
            #   startup:
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /accounts/login/
            #         port: *tandoorPort
            #       failureThreshold: 30
            #       periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities:
            #     drop:
            #       - ALL

    service:
      app:
        controller: *appname
        ports:
          http:
            port: 8000

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.pitower.link
        hosts:
          - host: &host house-hunter.pitower.link
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
