---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "pitower-link-staging"
  namespace: networking
spec:
  secretName: "pitower-link-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "pitower.link"
  dnsNames:
    - "pitower.link"
    - "*.pitower.link"
