---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go2rtc-config
  namespace: home-automation
data:
  go2rtc.yaml: |
    streams:
      basement:
        - rtsp://${BASEMENT_USER}:${BASEMENT_PASSWORD}@Camera-G100-7C13.iot:8554/ch1

    api:
      listen: ":1984"
      origin: "*"

    webrtc:
      listen: ":8555"
