# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: firefly-importer-secret
    labels:
        app.kubernetes.io/name: firefly-importer
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:stmny5FsplUdTH80n1OVHHLyy7hIR4+RWg3d+jcwdUw=,iv:fi1X8WX6NVXIaJ9N6kV+o7Gu8zos+gd5/PZWXNVrpt4=,tag:9a9+fk6MXbXE7ZtS4/Ogow==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:X/0foZAGKcpnDYebGnVh9i47xiHvV44x4vYfBVkcQE4=,iv:15LAsRl6dpgszaegD3qKMVA+FNcrEox/xd2WnVS1bro=,tag:hjulSnKs5VJ6c8M0+A4ttQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:BMDxJ1auybvO6N8mFe2/VNDlOPw=,iv:O0HUMk6v/rvAn3mQYm5F8zpmXpdLSnFvK2sSTWo4M4Y=,tag:mWUmyIC/A84Y+NfBptGezw==,type:str]
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:ImXWk3yI2+JVLqsxxmkBfjQnhPTF9vj/rJwSb2+C4/Zx5R9mj7lrbX+3TphYTwZS+griZaDzwQCW+0xwN4YOTrXCtc+tBwV3ICRhc2k5L+kLi6bveI9lK0CsWGmCcb7wW2IKs9C+GdlmBZLPxtSAQhfko8Dfs19w2VCnopYAVElxu8gm2XVWwY8gGZeDwxp5Ba3jCqHc3vfo3QqN0E6JK1MNy5ICgnUCYPlrhp8AEwa2RBbB9HFLe9QSldZCRJjvMwmWMKTTD+zQhJ35K3+bRYyG7XHqL7MwgoXGNTeeApSf/O4j2QN0aKy37bMghbN31kh7nEHH4kEGm0Ay4bQy0rZq8PTmJJ3EbsfJtm2mkAj0mOh3eYCn9zL2UKeWkz2LZ477W6b8A3TBb8Ttcg67SJzXJ7iXa7y+9VHcodvQ0DyqiSQDYpVCnngulG4k0b9r3Pqm1bqG9qXXeBiW1kurYf/NJ1O33xNRr8tsShOjwzm6ht8hpum+BTEYHgNo41NB7ysOqkvq5bMSErvPAzY39RcXLhMAoYwDjm7IpV15Skc2x4OdbgXqKoSUVe9K5xTuFm5TSF+gJT1IdJppOMstm3dIg816Ec5MWr9fwy/Pr5O+fk0n16oKxEHycgjRk8xOiVV0aNZwXRyvCDWWVeLTukjmuE1jirf9PDQw2k+br2IfqJbBNEhJB/SK8poArgul5jYWv+5Loe9P8n7wYhJPUfABZbzVNKOyQlz+vyRO7rr9xssUW2Kang1tIu7DbijKcjSiLDuP9j1IjOo3TFU8+1fY6uyZ3/4Sd+A2gVE2MDHxsDKocZn2KVe3vkWamDr2LQpDp+QzZ2OwcKM5s7bWJ4m7L1xj5AZg23QhqIBOxpVPMl9ZBac8Hc3l7bOwBD3lf7loRBR7pAaE96uRpHCyA18c4Z9yUg9XwYlPvPIazsEcmRJGj3TCaqnXX87pILySPWZExrF8yOmWXLEGOou56HHGMDRMlPlPVvkWtAUEL+LpTKeMksR0qYDd57z4GzS5cqtgE9P9Hc7nQPcdChb69/FjmBVZNOAmCYOQ+zEkG6aB01v+HbaP/MPTehwYLLRp0egIPfei44uoWpRz0FG/HUjYtI0EYEkUfVvyaZZBP0OmHXQ5a68g+g5sosfD1tfzlK+muGwea4ZFLTVOebjPthSrynDXzptTNoVYclb7XjuILoH510/KctErfT5Yb28v78aNHm0OIRe93pkpuAVhIqJr+e3VvnjaZ8aeR06vmqhZaUbL7PBR9ipeTEf6AI94Q8kRBLq4IBHaB5OjONVqGkD7ujA=,iv:AtzmqEC8gfuyXMoWhtRa4BIRMdkGK+4drKEhJ70AnK4=,tag:QMcVE56UdP+zMikz+cvqzg==,type:str]
    NORDIGEN_ID: ENC[AES256_GCM,data:ufvIqvhiCcVm4XwAmUs/UxgqzD1vDQsojBIKlU8+01OLx2Ja,iv:5SGZ1Y2Mh0RCTPpVu7DNT0ye1PEadN4VNzyweVU+j1M=,tag:bh4LNQ6gO/XsMVjZjCIKSQ==,type:str]
    NORDIGEN_KEY: ENC[AES256_GCM,data:aA49oWK9neF51pD2qXLRl9ivw3Vco00BlijW16yG9qDm7r7aJKRWyDdqCafO6393JwfVULNfJ3jahrUdcAhRwr2lMuebpgABep2Z3+u/yE/Cb42TQP93PlPRKSKWiUH8MEnhJfLN+YK8gLfws8HaouHUFGrmUDyyP+yH6Qzpv24=,iv:ZZGspfTp457+yPm7U/HFPxKLm0oEZFtGHRz6DoqLN5M=,tag:MitNLjOoFKvqhXdJb8OVuw==,type:str]
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:VGLKkaH0LReY8op2BTGi06fs2j6atg79DqnCYawjxOKbnvV6WzL/oz60K4Mbq/RXYkt3bpV+,iv:k0JOpvD1UpMU27dNLPXO/8d3T0Vkwhs1nLE3WLtkgJI=,tag:mcLIrIvrvSwBPp6UHWtsew==,type:str]
    IMPORT_DIR_ALLOWLIST: ENC[AES256_GCM,data:fSV6q6mt1A==,iv:ziGtZDsYbq7qivSM4DwVA53CkE7lyPYdwDfYF52ZILs=,tag:csCKSGDO/vo4/tbajyVzVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1E4ckVMSDdnUzZWVzgw
            NHVpWTVaNGxGZVRUSW04N1B1V0E3THpDZWo4ClE3QVFDMGZQVm9kcm1HU3lldDhU
            bkRMNVFwbUZaVTFQT1YrM21UTUVBK2MKLS0tIFM5YTBRa3V1R2tNVnRoQ2gvVzk5
            UWJoVjV6bkUxM3dNNU9BREZMeGtCRTgKIqoRQLlZ+KS4/SLVkcCfmWv/5mKjX7Fb
            iKQGZuuJtfrQ238GaecEZn9rN2F3vm1SogKdtwduBmdQysYN8g4Kug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T00:19:22Z"
    mac: ENC[AES256_GCM,data:U6VyTW4TW+Ka7WCMuGJiYGUGV6bpUOOCAR7pjZEzfwWd6PAr0snyTN+GGR4s5gGm5VUHQgby49sCw/+kWcJSSNZUUD4NUlAEPoRkVLcsSre9KYDnB2heFXaNgh6UDRC4KtR6kgyifkbagrqXv75fe9Z4cgpb8uD8rrW2TaSWoYI=,iv:X2ZZzRkmv6SQT/EXFrjrDuve8LHoyd2y7si3iDPHDWk=,tag:zabFY0yTCuHnVXdqS+dI5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
