---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzdb-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
