---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc
resources:
  - namespace.yaml
helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
    releaseName: arc
    namespace: arc
    valuesFile: values.yaml
    includeCRDs: true

patches:
  - target:
      kind: Deployment
      name: arc-gha-rs-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: arc-gha-rs-controller
        annotations:
          reloader.stakater.com/auto: "true"
