---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-config
  namespace: security
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: authelia-configmap
            items:
              - key: configuration.yaml
                templateAs: Values
          target: Data

  data:
    - secretKey: authelia_session_secret
      remoteRef:
        key: /security/authelia/session_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_storage_encryption_key
      remoteRef:
        key: /security/authelia/storage_encryption_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_jwt_secret
      remoteRef:
        key: /security/authelia/jwt_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_oidc_hmac_secret
      remoteRef:
        key: /security/authelia/oidc_hmac_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_jelly_id
      remoteRef:
        key: /security/authelia/jelly_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_jelly_secret
      remoteRef:
        key: /security/authelia/jelly_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_grafana_secret
      remoteRef:
        key: /security/authelia/grafana_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: encoded_authelia_oidc_issuer_key
      remoteRef:
        key: /security/authelia/oidc_issuer_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_miniflux_secret
      remoteRef:
        key: /security/authelia/miniflux_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_mealie_secret
      remoteRef:
        key: /security/authelia/mealie_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_paperless_secret
      remoteRef:
        key: /security/authelia/paperless_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_ghostfolio_secret
      remoteRef:
        key: /security/authelia/ghostfolio_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: authelia_autobrr_secret
      remoteRef:
        key: /security/authelia/autobrr_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: authelia-secrets

  # dataFrom will fetch all secrets that are inside the `secretsPath`. When `recursive` is
  # enabled, it will also fetch all secrets recursively in sub-directories.
  data:
    - secretKey: LLDAP_BIND_PASSWORD
      remoteRef:
        key: /security/authelia/LLDAP_BIND_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: LLDAP_BIND_USER_DN
      remoteRef:
        key: /security/authelia/LLDAP_BIND_USER_DN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
