---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: git
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: forgejo-admin-secret
    template:
      data:
        username: "{{ .ADMIN_USERNAME }}"
        password: "{{ .ADMIN_PASSWORD }}"
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: /git/forgejo/ADMIN_USERNAME
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /git/forgejo/ADMIN_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc
  namespace: git
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: forgejo-oidc-secret
    template:
      data:
        key: "{{ .OIDC_CLIENT_ID }}"
        secret: "{{ .OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /git/forgejo/OIDC_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /git/forgejo/OIDC_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
