---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - externalsecret.yaml
  - httproute.yaml
  - dragonfly.yaml
components:
  - ../../../../components/cnpg-db-shared
  - ../../../../components/pvc
  - ../../../../components/kopiur
configMapGenerator:
  - name: cnpg-db-config
    literals:
      - APP_NAME=forgejo
      - SECRET_NAME=forgejo-db-secret
      - CNPG_SECRET_KEY=shared-forgejo
      - DB_SCHEME=postgresql
  - name: pvc-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=forgejo-pvc
      - CLAIM_NAME=forgejo
      - STORAGE_SIZE=10Gi
  - name: kopiur-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=forgejo-kopiur
      - CLAIM_NAME=forgejo
helmCharts:
  - name: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    version: 17.1.5
    releaseName: forgejo
    namespace: dev
    valuesFile: values.yaml
