---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  path: ./kubernetes/pitower/apps/networking/tailscale/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: true
  # dependsOn:
  #   - name: cloudnative-pg
  #   - name: external-secrets
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-connectors
  namespace: flux-system
spec:
  path: ./kubernetes/pitower/apps/networking/tailscale/connectors
  prune: true
  sourceRef:
    kind: GitRepository
    name: pitower
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: true
  dependsOn:
    - name: tailscale