---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - externalsecret.yaml
components:
  - ../../../../components/volsync
configMapGenerator:
  - name: hermes-config
    options:
      disableNameSuffixHash: true
    files:
      - config.yaml=config.yaml
  - name: hermes-agentmemory-plugin
    options:
      disableNameSuffixHash: true
    files:
      - __init__.py=plugin/__init__.py
      - plugin.yaml=plugin/plugin.yaml
  - name: volsync-config
    options:
      disableNameSuffixHash: true
    literals:
      - APP_NAME=hermes
      - CLAIM_NAME=hermes
      - SECRET_NAME=hermes-volsync
      - STORAGE_SIZE=5Gi
      - RESTIC_REPO=s3:https://s3.eu-central-2.amazonaws.com/pitower-volsync-backups/ai/hermes
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 5.0.1
    releaseName: hermes
    namespace: ai
    valuesFile: values.yaml
