garage_rpc_secret: ENC[AES256_GCM,data:YmO7kBvXS7yueNzP7CtLgfjoeMbohU3LFvFq+bgC2d3u6hLtONXT1Wj2S6+VzIGFsi+CDKR69ijCajfEoRrAgQ==,iv:w9GsQJgCb/40+n+aG+MZHYhHurXFcDVbIaCOP75Wt3E=,tag:vL5G4jcomW4/NbOmFqEddQ==,type:str]
garage_admin_token: ENC[AES256_GCM,data:P8wR3hqMsfPwZApOjRQOZ1X+T4chmvMEJwpNSeHpAc+rbeVyEYYD8Ah3fRs=,iv:beto1BKEFIJxaOpDIC+71bEOJdvp57LdgC/IE0MwNAI=,tag:Hfnu28nog0kjISWKryRtNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRd1dxZnRCa2FDR09Ea0dT
            R0hTZVZBYnN1N25oK0lGNWl3cnh6VWhvanljCklPQmczTjNTQU1xYmZOUHAyVGx0
            VHJCMzRkcFlFZVorRTM2L05lMXE1UmcKLS0tIEY1NWpYa0NjSHdEQklsYUsyRlo4
            bVFlckFZbm1KcGg2eUJtajBWSkVsTU0KHqa50BcR8+SZZ9KBY/ZX9Wk2vmMyD6so
            5OA6QlbfsZqccHcbTMVmDadrNDlwp5AKYCbPv4pYPMJdf3EUsptmWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
    lastmodified: "2026-07-23T20:57:22Z"
    mac: ENC[AES256_GCM,data:Dr9A3HYNSsr+2PJ7YJYAwtxGpyXDvCw/b4xwNYDYLWRPuGsubnaz6NfM3wGR8WMMB8jL+DPy2TTybWmuDOXpBdb4wIvsyFcz30X0Jby+SVcD9/oPqkkkoaSk/jDzqeL0J46UuP/v26SzWKgcK4lhuUx/tdS/XaLhpaCCc0uzWXg=,iv:OETnOfdtQCxOSv0VCRUESA1LDDKDg+8VxgU9/HSmQws=,tag:nLG12QkMgx46ZP0N8SzzLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
