---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app
  namespace: arc-runners
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: arc-github-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .app_id }}"
        github_app_installation_id: "{{ .installation_id }}"
        github_app_private_key: "{{ .private_key }}"
  data:
    - secretKey: app_id
      remoteRef:
        key: /arc/github-app/app_id
    - secretKey: installation_id
      remoteRef:
        key: /arc/github-app/installation_id
    - secretKey: private_key
      remoteRef:
        key: /arc/github-app/private_key
