apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions
resources:
  - ./podmonitor.yaml
  # - ./rbac.yaml

helmCharts:
  - name: pitower
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    version: 0.11.0
    releaseName: pitower-runners
    namespace: actions
    valuesFile: values.yaml
