apiVersion: v1
kind: Secret
metadata:
    name: wg-secret
    namespace: vpn
stringData:
    privatekey: ENC[AES256_GCM,data:oDgFopA28lYG9j5pW5kX1TwCYuxZXSADB+S7xQT1Z8VSCJnITBdtmcPg/1E=,iv:d8+D+o/dgxwZuDwUJnUwtTmrZJnNztDoaODko8SXF+U=,tag:opr8WefwYI2nKoQQsarCcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tkaddc3hgjx0eagjl6mqpxvzzkerd44e34rua6gzucv6emr5f5fs4mlu67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY0krS2dxbDZiM2FySVlG
            RFVlYXhQN05DMEJwWVozVDRlc1FOVFBPNFV3CmI5TE5aR2ZDZUx3ck1xVVlHVmgr
            T09KZ0dmNEt6NzlIdUpobWhQSVBwUDgKLS0tIHh0ZGFsUUpaViswblpneE5OTUlV
            UTc5VURwRit0alduS0pYY0p6M0VTRDQKC7y6NI+vZd45+bvHjfF//VfAxoHMJCN5
            0NzrPzwjNJxdO8knfomyucO5h6jMUSEcvzySi0SgLu/TgtjS93QESA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T20:59:11Z"
    mac: ENC[AES256_GCM,data:V7EyuXUvVDsZq62Q5A0uq7HowPfF8JyA6lsHJnoOLzbX31+2RyLxBlkUq4j3YkeqitINIw99kS90kC9T0xGvt7C978q3MDhV3GbyZGh6TEAiB2rf6+xCj6J3YI4jUOmx0PhC5ziSwEgt4kyWH1AXlzDlqcxE0K7xXewUwarqig8=,iv:XmsZk5QsUmmgAMEpuXZbSVw71FLhET2VfqTajEMfRHo=,tag:W2tCz8elbJG0SbzU3oVUvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
