---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webterm-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: webterm-secrets
    creationPolicy: Owner
  data:
    - secretKey: WEBTERM_SESSION_SECRET
      remoteRef:
        key: /dev/webterm/WEBTERM_SESSION_SECRET
