---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-1password
  namespace: security
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: authelia-configmap
            items:
              - key: configuration.yaml
                templateAs: Values
          target: Data

  dataFrom:
    - extract:
        key: authelia
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authelia_$1"
    - extract:
        key: authelia
        decodingStrategy: Auto
        conversionStrategy: Default
        metadataPolicy: None
      rewrite:
        - regexp:
            source: "(.*)"
            target: "encoded_authelia_$1"

# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: authelia
#   namespace: security
