---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - prometheusrule.yaml

helmCharts:
  - name: volsync
    repo: https://backube.github.io/helm-charts/
    version: 0.12.1
    releaseName: volsync
    valuesFile: values.yaml
