name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "docs/requirements.txt"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: home-ops
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
          cache: pip

      - run: pip install -r docs/requirements.txt

      - run: mkdocs gh-deploy --force
