name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - alexa
          - general
      fail-fast: false
    name: Apply (${{ matrix.stack }})
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: eu-central-2

      - uses: dflook/terraform-apply@5489b988934a50bf1489d5b7c5253b46520a7dca # v2
        with:
          path: terraform/${{ matrix.stack }}
          label: ${{ matrix.stack }}
          auto_approve: true
