name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - alexa
          - bootstrap
          - general
      fail-fast: false
    name: Apply (${{ matrix.stack }})
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: eu-central-2

      - uses: dflook/terraform-apply@5489b988934a50bf1489d5b7c5253b46520a7dca # v2
        with:
          path: terraform/${{ matrix.stack }}
          label: ${{ matrix.stack }}
          auto_approve: true
