# Test self-hosted runner
name: Test

on:
  pull_request:
    branches: [main]

env:
  AWS_REGION: "eu-central-2"

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: default
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Test"
