---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
helmCharts:
  - name: app-template
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.12.2
    releaseName: nginx-external
    valuesFile: values.yaml
